// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';
import {desktop} from '../models';

export function Aliases():Promise<Array<app.AliasView>>;

export function ApplySync(arg1:app.SyncInput):Promise<app.SyncResult>;

export function BeforeClose(arg1:context.Context):Promise<boolean>;

export function BindTarget(arg1:app.AliasTargetInput):Promise<app.AliasView>;

export function Bindings():Promise<desktop.Bindings>;

export function DeleteAlias(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DesktopPrefs():Promise<app.DesktopPrefsView>;

export function DoctorRun():Promise<app.DoctorRunResult>;

export function ExportConfig():Promise<app.ConfigExportView>;

export function ImportConfig(arg1:app.ConfigImportInput):Promise<app.ConfigImportResult>;

export function ImportProviders(arg1:app.ProviderImportInput):Promise<app.ProviderImportResult>;

export function Meta():Promise<Record<string, string>>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function Overview():Promise<app.Overview>;

export function PreviewSync(arg1:app.SyncInput):Promise<app.SyncPreview>;

export function Providers():Promise<Array<app.ProviderView>>;

export function ProxySettings():Promise<app.ProxySettingsView>;

export function ProxyStatus():Promise<app.ProxyStatusView>;

export function RefreshProviderModels(arg1:app.ProviderRefreshModelsInput):Promise<app.ProviderSaveResult>;

export function RequestTraces(arg1:number):Promise<Array<app.RequestTrace>>;

export function SaveAlias(arg1:app.AliasUpsertInput):Promise<app.AliasView>;

export function SaveDesktopPrefs(arg1:context.Context,arg2:app.DesktopPrefsInput):Promise<app.DesktopPrefsSaveResult>;

export function SavePrefs(arg1:app.DesktopPrefsInput):Promise<app.DesktopPrefsSaveResult>;

export function SaveProvider(arg1:app.ProviderUpsertInput):Promise<app.ProviderSaveResult>;

export function SaveProxySettings(arg1:app.ProxySettingsInput):Promise<app.ProxySettingsSaveResult>;

export function Service():Promise<app.Service>;

export function SetProviderState(arg1:app.ProviderStateInput):Promise<app.ProviderView>;

export function SetTargetState(arg1:app.AliasTargetInput):Promise<app.AliasView>;

export function SetVersion(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartProxy():Promise<app.ProxyStatusView>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopProxy():Promise<app.ProxyStatusView>;

export function SyncDesktopPreferences(arg1:context.Context):Promise<void>;

export function TraceList(arg1:app.RequestTraceListInput):Promise<app.RequestTraceListResult>;

export function UnbindTarget(arg1:app.AliasTargetInput):Promise<app.AliasView>;
