// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Aliases() {
  return window['go']['desktop']['App']['Aliases']();
}

export function ApplySync(arg1) {
  return window['go']['desktop']['App']['ApplySync'](arg1);
}

export function BeforeClose(arg1) {
  return window['go']['desktop']['App']['BeforeClose'](arg1);
}

export function BindTarget(arg1) {
  return window['go']['desktop']['App']['BindTarget'](arg1);
}

export function Bindings() {
  return window['go']['desktop']['App']['Bindings']();
}

export function DeleteAlias(arg1) {
  return window['go']['desktop']['App']['DeleteAlias'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['desktop']['App']['DeleteProvider'](arg1);
}

export function DesktopPrefs() {
  return window['go']['desktop']['App']['DesktopPrefs']();
}

export function DoctorRun() {
  return window['go']['desktop']['App']['DoctorRun']();
}

export function ExportConfig() {
  return window['go']['desktop']['App']['ExportConfig']();
}

export function ImportConfig(arg1) {
  return window['go']['desktop']['App']['ImportConfig'](arg1);
}

export function ImportProviders(arg1) {
  return window['go']['desktop']['App']['ImportProviders'](arg1);
}

export function Meta() {
  return window['go']['desktop']['App']['Meta']();
}

export function Overview() {
  return window['go']['desktop']['App']['Overview']();
}

export function PreviewSync(arg1) {
  return window['go']['desktop']['App']['PreviewSync'](arg1);
}

export function Providers() {
  return window['go']['desktop']['App']['Providers']();
}

export function ProxySettings() {
  return window['go']['desktop']['App']['ProxySettings']();
}

export function ProxyStatus() {
  return window['go']['desktop']['App']['ProxyStatus']();
}

export function RequestTraces(arg1) {
  return window['go']['desktop']['App']['RequestTraces'](arg1);
}

export function SaveAlias(arg1) {
  return window['go']['desktop']['App']['SaveAlias'](arg1);
}

export function SaveDesktopPrefs(arg1, arg2) {
  return window['go']['desktop']['App']['SaveDesktopPrefs'](arg1, arg2);
}

export function SavePrefs(arg1) {
  return window['go']['desktop']['App']['SavePrefs'](arg1);
}

export function SaveProvider(arg1) {
  return window['go']['desktop']['App']['SaveProvider'](arg1);
}

export function SaveProxySettings(arg1) {
  return window['go']['desktop']['App']['SaveProxySettings'](arg1);
}

export function Service() {
  return window['go']['desktop']['App']['Service']();
}

export function SetProviderState(arg1) {
  return window['go']['desktop']['App']['SetProviderState'](arg1);
}

export function SetTargetState(arg1) {
  return window['go']['desktop']['App']['SetTargetState'](arg1);
}

export function SetVersion(arg1) {
  return window['go']['desktop']['App']['SetVersion'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['desktop']['App']['Shutdown'](arg1);
}

export function StartProxy() {
  return window['go']['desktop']['App']['StartProxy']();
}

export function Startup(arg1) {
  return window['go']['desktop']['App']['Startup'](arg1);
}

export function StopProxy() {
  return window['go']['desktop']['App']['StopProxy']();
}

export function SyncDesktopPreferences(arg1) {
  return window['go']['desktop']['App']['SyncDesktopPreferences'](arg1);
}

export function UnbindTarget(arg1) {
  return window['go']['desktop']['App']['UnbindTarget'](arg1);
}
