package lifecycle

import (
	"fmt"
	"strings"

	"github.com/Apale7/opencode-provider-switch/internal/config"
)

const (
	DiscoverySkip            = "skip"
	DiscoveryError           = "error"
	DiscoveryEmpty           = "empty"
	DiscoveryIncomplete      = "incomplete"
	DiscoveryTrustedComplete = "trusted_complete"
)

// PlanDiscoveryReconcile plans ownership-aware auto alias maintenance for one provider.
// Non-trusted observations produce zero Alias diff.
func PlanDiscoveryReconcile(base *config.Config, baseRevision, providerID string, observation DiscoveryObservation) (Result, error) {
	if base == nil {
		return Result{}, fmt.Errorf("lifecycle: config is required")
	}
	providerID = strings.TrimSpace(providerID)
	if providerID == "" {
		return Result{}, fmt.Errorf("lifecycle: provider id is required")
	}

	plan := emptyPlan(OpDiscoverySync, baseRevision)
	plan.RequestedChanges = append(plan.RequestedChanges, Change{
		ID:         "requested:discovery:" + providerID,
		Kind:       ChangeUpdate,
		Source:     SourceRequested,
		Entity:     EntityProvider,
		ReasonCode: ReasonSystemTargetReconcile,
		Params:     params("providerId", providerID, "status", observation.Status),
	})

	status := strings.TrimSpace(observation.Status)
	if status == "" {
		status = DiscoverySkip
	}

	// Untrusted / incomplete / empty / error / skip => zero alias diff.
	if status != DiscoveryTrustedComplete {
		plan.PreservedIssues = append(plan.PreservedIssues, Issue{
			ID:          "preserved:discovery_untrusted",
			Code:        ReasonDiscoveryUntrusted,
			Disposition: DispositionPreserved,
			Params:      params("providerId", providerID, "status", status),
		})
		finalizePlan(&plan)
		plan.Executable = true
		plan.NoOp = true
		return Result{Plan: plan, Candidate: CloneConfig(base)}, nil
	}

	models := map[string]bool{}
	for _, m := range observation.Models {
		m = strings.TrimSpace(m)
		if m != "" {
			models[m] = true
		}
	}
	if len(models) == 0 {
		// Trusted complete but empty still must not prune.
		plan.PreservedIssues = append(plan.PreservedIssues, Issue{
			ID:          "preserved:discovery_empty_trusted",
			Code:        ReasonDiscoveryUntrusted,
			Disposition: DispositionPreserved,
			Params:      params("providerId", providerID, "status", DiscoveryEmpty),
		})
		finalizePlan(&plan)
		plan.Executable = true
		plan.NoOp = true
		return Result{Plan: plan, Candidate: CloneConfig(base)}, nil
	}

	// Only system-owned targets for this provider may be pruned when model missing.
	for ai, alias := range base.Aliases {
		if !alias.AutoGenerated || alias.Locked {
			continue
		}
		for ti, target := range alias.Targets {
			if target.Provider != providerID || !TargetSystemOwned(alias, target) {
				continue
			}
			if models[target.Model] {
				continue
			}
			plan.AutomaticChanges = append(plan.AutomaticChanges, Change{
				ID:         fmt.Sprintf("auto:reconcile_remove_target:%d:%d", ai, ti),
				Kind:       ChangeRemove,
				Source:     SourceAutomatic,
				Entity:     EntityAliasTarget,
				ReasonCode: ReasonSystemTargetReconcile,
				Path:       fmt.Sprintf("/config/aliases/%d/targets/%d", ai, ti),
				Params: params(
					"alias", alias.Alias,
					"providerId", target.Provider,
					"model", target.Model,
					"aliasIndex", ai,
					"targetIndex", ti,
				),
			})
		}
	}

	// Empty pure auto aliases after system target removal.
	// Applied during apply; mark for aliases where all remaining targets for this provider would be removed
	// and no other targets remain.
	for ai, alias := range base.Aliases {
		if !PureAutoAlias(alias) {
			continue
		}
		remaining := 0
		removed := 0
		for _, t := range alias.Targets {
			if t.Provider == providerID && TargetSystemOwned(alias, t) && !models[t.Model] {
				removed++
				continue
			}
			remaining++
		}
		if removed > 0 && remaining == 0 {
			plan.AutomaticChanges = append(plan.AutomaticChanges, Change{
				ID:         "auto:reconcile_empty_alias:" + alias.Alias,
				Kind:       ChangeRemove,
				Source:     SourceAutomatic,
				Entity:     EntityAlias,
				ReasonCode: ReasonEmptyAutoAliasCleanup,
				Path:       fmt.Sprintf("/config/aliases/%d", ai),
				Params:     params("alias", alias.Alias, "providerId", providerID),
			})
		}
	}

	finalizePlan(&plan)
	if !plan.Executable {
		return Result{Plan: plan}, nil
	}
	if len(plan.AutomaticChanges) == 0 {
		plan.NoOp = true
		return Result{Plan: plan, Candidate: CloneConfig(base)}, nil
	}
	candidate := applyDiscoveryReconcile(base, providerID, models, plan)
	return Result{Plan: plan, Candidate: candidate}, nil
}

func applyDiscoveryReconcile(base *config.Config, providerID string, models map[string]bool, plan Plan) *config.Config {
	cfg := CloneConfig(base)
	deleteAliases := map[string]bool{}
	for _, ch := range plan.AutomaticChanges {
		if ch.Entity == EntityAlias && ch.ReasonCode == ReasonEmptyAutoAliasCleanup {
			if a, ok := ch.Params["alias"].(string); ok {
				deleteAliases[a] = true
			}
		}
	}

	nextAliases := make([]config.Alias, 0, len(cfg.Aliases))
	for _, alias := range cfg.Aliases {
		if deleteAliases[alias.Alias] {
			continue
		}
		if !alias.AutoGenerated || alias.Locked {
			nextAliases = append(nextAliases, alias)
			continue
		}
		nextTargets := make([]config.Target, 0, len(alias.Targets))
		for _, t := range alias.Targets {
			if t.Provider == providerID && TargetSystemOwned(alias, t) && !models[t.Model] {
				continue
			}
			nextTargets = append(nextTargets, t)
		}
		alias.Targets = nextTargets
		if PureAutoAlias(alias) && len(alias.Targets) == 0 && deleteAliases[alias.Alias] {
			continue
		}
		// If emptied but not planned for delete, keep empty pure auto only if not pure empty cleanup.
		if PureAutoAlias(alias) && len(alias.Targets) == 0 {
			// Drop only when we planned empty cleanup.
			if deleteAliases[alias.Alias] {
				continue
			}
		}
		nextAliases = append(nextAliases, alias)
	}
	cfg.Aliases = nextAliases
	return cfg
}

// PlanProviderDisabled is a zero-diff availability change (disabled is not missing).
func PlanProviderDisabled(base *config.Config, baseRevision, providerID string, disabled bool) (Result, error) {
	if base == nil {
		return Result{}, fmt.Errorf("lifecycle: config is required")
	}
	providerID = strings.TrimSpace(providerID)
	plan := emptyPlan("provider.state", baseRevision)
	found := false
	for i, p := range base.Providers {
		if p.ID != providerID {
			continue
		}
		found = true
		if p.Disabled == disabled {
			finalizePlan(&plan)
			plan.Executable = true
			plan.NoOp = true
			return Result{Plan: plan, Candidate: CloneConfig(base)}, nil
		}
		plan.RequestedChanges = append(plan.RequestedChanges, Change{
			ID:         "requested:provider_disabled:" + providerID,
			Kind:       ChangeUpdate,
			Source:     SourceRequested,
			Entity:     EntityProvider,
			ReasonCode: "provider_disabled",
			Path:       fmt.Sprintf("/config/providers/%d/disabled", i),
			Params:     params("providerId", providerID, "disabled", disabled),
		})
		break
	}
	if !found {
		plan.Blockers = append(plan.Blockers, Issue{
			ID:          "blocker:provider_missing",
			Code:        ReasonProviderMissing,
			Disposition: DispositionBlocker,
			Params:      params("providerId", providerID),
		})
		finalizePlan(&plan)
		return Result{Plan: plan}, nil
	}
	finalizePlan(&plan)
	if !plan.Executable {
		return Result{Plan: plan}, nil
	}
	candidate := CloneConfig(base)
	for i := range candidate.Providers {
		if candidate.Providers[i].ID == providerID {
			candidate.Providers[i].Disabled = disabled
			break
		}
	}
	// Zero alias diff invariant: aliases unchanged.
	return Result{Plan: plan, Candidate: candidate}, nil
}
