package lifecycle

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/Apale7/opencode-provider-switch/internal/config"
)

func baseConfig() *config.Config {
	cfg := config.Default()
	cfg.Providers = []config.Provider{
		{ID: "p1", BaseURL: "https://p1.example/v1", Groups: []config.ProviderGroup{{ID: "default", Protocol: config.ProtocolOpenAIResponses}}},
		{ID: "p2", BaseURL: "https://p2.example/v1", Groups: []config.ProviderGroup{{ID: "default", Protocol: config.ProtocolOpenAIResponses}}},
	}
	cfg.ProviderPriority = []string{"p1", "p2"}
	cfg.Aliases = []config.Alias{
		{
			Alias: "sys-model", AutoGenerated: true, Enabled: true,
			Targets: []config.Target{
				{Provider: "p1", Group: "default", Model: "sys-model", Enabled: true, AutoGenerated: true},
				{Provider: "p2", Group: "default", Model: "sys-model", Enabled: true, AutoGenerated: true},
			},
		},
		{
			Alias: "manual", Enabled: true,
			Targets: []config.Target{{Provider: "p1", Group: "default", Model: "m", Enabled: true}},
		},
		{
			Alias: "mixed", AutoGenerated: true, Enabled: true,
			Targets: []config.Target{
				{Provider: "p1", Group: "default", Model: "a", Enabled: true, AutoGenerated: true},
				{Provider: "p1", Group: "default", Model: "b", Enabled: true, AutoGenerated: false},
			},
		},
		{
			Alias: "locked", AutoGenerated: true, Locked: true, Enabled: true,
			Targets: []config.Target{{Provider: "p1", Group: "default", Model: "L", Enabled: true, AutoGenerated: true}},
		},
	}
	cfg.RequestRewriteRules = []config.RequestRewriteRule{
		{Name: "multi", Alias: "manual", ProviderGroups: []config.ProviderGroupSelector{{Provider: "p1", Group: "default"}, {Provider: "p2", Group: "default"}}, Enabled: true},
		{Name: "single", Alias: "manual", ProviderGroups: []config.ProviderGroupSelector{{Provider: "p1", Group: "default"}}, Enabled: true},
		{Name: "wild", Alias: "other", ProviderGroups: []config.ProviderGroupSelector{}, Enabled: true},
	}
	return cfg
}

func TestPlanProviderRemoveSystemAndPriorityAndNarrow(t *testing.T) {
	cfg := baseConfig()
	// Resolve protected targets and singleton rewrite.
	selections := []Selection{
		{ChoiceID: "protected_target:1:0", OptionID: OptionRemoveTarget}, // manual
		{ChoiceID: "protected_target:2:1", OptionID: OptionRemoveTarget}, // mixed protected b
		{ChoiceID: "protected_target:3:0", OptionID: OptionDeleteAlias},  // locked
		{ChoiceID: "singleton_rewrite:1", OptionID: OptionKeepDormant},
	}
	result, err := PlanProviderRemove(cfg, "rev-base", "p1", selections)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("expected executable plan, got blockers=%+v choices=%+v", result.Plan.Blockers, result.Plan.Choices)
	}
	if result.Candidate == nil {
		t.Fatal("missing candidate")
	}
	if result.Candidate.FindProvider("p1") != nil {
		t.Fatal("provider p1 still present")
	}
	for _, id := range result.Candidate.ProviderPriority {
		if id == "p1" {
			t.Fatal("priority retained p1")
		}
	}
	// multi rewrite narrowed to [p2]
	var multi *config.RequestRewriteRule
	for i := range result.Candidate.RequestRewriteRules {
		if result.Candidate.RequestRewriteRules[i].Name == "multi" {
			multi = &result.Candidate.RequestRewriteRules[i]
		}
	}
	if multi == nil || len(multi.ProviderGroups) != 1 || multi.ProviderGroups[0].Provider != "p2" || multi.ProviderGroups[0].Group != "default" {
		t.Fatalf("multi rewrite not narrowed: %+v", multi)
	}
	// singleton kept dormant with p1
	var single *config.RequestRewriteRule
	for i := range result.Candidate.RequestRewriteRules {
		if result.Candidate.RequestRewriteRules[i].Name == "single" {
			single = &result.Candidate.RequestRewriteRules[i]
		}
	}
	if single == nil || len(single.ProviderGroups) != 1 || single.ProviderGroups[0].Provider != "p1" || single.ProviderGroups[0].Group != "default" {
		t.Fatalf("singleton must stay dormant, got %+v", single)
	}
	// wildcard unchanged
	for _, rule := range result.Candidate.RequestRewriteRules {
		if rule.Name == "wild" && len(rule.ProviderGroups) != 0 {
			t.Fatalf("wildcard changed: %+v", rule)
		}
	}
	// locked alias deleted via selection
	if idx, _ := RequireUniqueAlias(result.Candidate, "locked"); idx >= 0 {
		t.Fatal("locked alias should be deleted by selection")
	}
	// pure auto sys-model still has p2 target
	idx, err := RequireUniqueAlias(result.Candidate, "sys-model")
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Candidate.Aliases[idx].Targets) != 1 || result.Candidate.Aliases[idx].Targets[0].Provider != "p2" {
		t.Fatalf("sys-model targets=%+v", result.Candidate.Aliases[idx].Targets)
	}
}

func TestPlanProviderRemoveBlocksWithoutSelections(t *testing.T) {
	cfg := baseConfig()
	result, err := PlanProviderRemove(cfg, "rev", "p1", nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("protected targets must block execute")
	}
	if result.Candidate != nil {
		t.Fatal("candidate must be nil when not executable")
	}
	if len(result.Plan.Choices) == 0 {
		t.Fatal("expected required choices")
	}
}

func TestPlanProviderRemoveNeverExpandsSingletonToWildcard(t *testing.T) {
	cfg := config.Default()
	cfg.Providers = []config.Provider{{ID: "only", BaseURL: "https://x.example/v1", Groups: []config.ProviderGroup{{ID: config.DefaultGroupID, Protocol: config.ProtocolOpenAIResponses}}}}
	cfg.RequestRewriteRules = []config.RequestRewriteRule{
		{Name: "s", Alias: "a", ProviderGroups: []config.ProviderGroupSelector{{Provider: "only", Group: config.DefaultGroupID}}, Enabled: true},
	}
	result, err := PlanProviderRemove(cfg, "rev", "only", nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("singleton rewrite must require choice")
	}
	found := false
	for _, c := range result.Plan.Choices {
		if c.Code == ReasonSingletonRewrite {
			found = true
			for _, opt := range c.Options {
				if opt.ID == OptionKeepDormant || opt.ID == OptionDisableRule || opt.ID == OptionDeleteRule || opt.ID == OptionReplaceProviderGroups {
					continue
				}
				t.Fatalf("unexpected option %q", opt.ID)
			}
		}
	}
	if !found {
		t.Fatal("missing singleton rewrite choice")
	}
	// Automatic changes must not include rewriting singleton to empty.
	for _, ch := range result.Plan.AutomaticChanges {
		if ch.ReasonCode == ReasonRewriteSelectorNarrow {
			t.Fatalf("singleton must not be auto-narrowed: %+v", ch)
		}
	}
}

func TestPlanProviderRemoveEmptyPureAutoAlias(t *testing.T) {
	cfg := config.Default()
	cfg.Providers = []config.Provider{{ID: "p1", BaseURL: "https://x.example/v1", Groups: []config.ProviderGroup{{ID: config.DefaultGroupID, Protocol: config.ProtocolOpenAIResponses}}}}
	cfg.Aliases = []config.Alias{{
		Alias: "only-sys", AutoGenerated: true, Enabled: true,
		Targets: []config.Target{{Provider: "p1", Model: "only-sys", Enabled: true, AutoGenerated: true}},
	}}
	result, err := PlanProviderRemove(cfg, "rev", "p1", nil)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("should be executable: %+v", result.Plan.Blockers)
	}
	if len(result.Candidate.Aliases) != 0 {
		t.Fatalf("empty pure auto alias retained: %+v", result.Candidate.Aliases)
	}
}

func TestPlanAliasRemoveKeepsRewriteByDefaultChoice(t *testing.T) {
	cfg := baseConfig()
	// Alias manual is referenced by multi+single rewrite rules.
	selections := []Selection{
		{ChoiceID: "rewrite_on_alias_remove:0", OptionID: OptionKeepRule},
		{ChoiceID: "rewrite_on_alias_remove:1", OptionID: OptionDisableRule},
	}
	result, err := PlanAliasRemove(cfg, "rev", "manual", selections, ExternalRefs{
		OpenCodeModel: "manual",
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("plan=%+v", result.Plan)
	}
	if _, err := RequireUniqueAlias(result.Candidate, "manual"); err == nil {
		t.Fatal("alias should be removed")
	}
	var multi, single *config.RequestRewriteRule
	for i := range result.Candidate.RequestRewriteRules {
		r := &result.Candidate.RequestRewriteRules[i]
		switch r.Name {
		case "multi":
			multi = r
		case "single":
			single = r
		}
	}
	if multi == nil || multi.Alias != "manual" {
		t.Fatalf("keep rule lost: %+v", multi)
	}
	if single == nil || single.Enabled {
		t.Fatalf("disable rule failed: %+v", single)
	}
	foundOpenCode := false
	for _, issue := range result.Plan.PreservedIssues {
		if issue.Code == ReasonOpenCodeWeakRef {
			foundOpenCode = true
		}
		if issue.Code == ReasonDirectFallbackPossible {
			if v, _ := issue.Params["directFallbackPossible"].(bool); !v {
				t.Fatal("direct fallback flag missing")
			}
		}
	}
	if !foundOpenCode {
		t.Fatal("expected opencode weak ref preserved issue")
	}
}

func TestPlanAliasUpgradeOnlyOwnershipFlags(t *testing.T) {
	cfg := baseConfig()
	before := cfg.Aliases[0]
	result, err := PlanAliasUpgrade(cfg, "rev", "sys-model")
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable || result.Plan.NoOp {
		t.Fatalf("plan=%+v", result.Plan)
	}
	idx, err := RequireUniqueAlias(result.Candidate, "sys-model")
	if err != nil {
		t.Fatal(err)
	}
	after := result.Candidate.Aliases[idx]
	if after.AutoGenerated || after.Locked {
		t.Fatalf("ownership not cleared: %+v", after)
	}
	if after.Alias != before.Alias || after.Enabled != before.Enabled || len(after.Targets) != len(before.Targets) {
		t.Fatalf("non-ownership fields changed: before=%+v after=%+v", before, after)
	}
	for i := range after.Targets {
		if after.Targets[i].AutoGenerated {
			t.Fatal("target ownership not cleared")
		}
		if after.Targets[i].Provider != before.Targets[i].Provider || after.Targets[i].Model != before.Targets[i].Model {
			t.Fatal("target identity changed")
		}
	}
}

func TestPlanAliasMutateGateRejectsAuto(t *testing.T) {
	cfg := baseConfig()
	result, err := PlanAliasMutateGate(cfg, "rev", "sys-model", "bind")
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("auto alias mutation must be blocked")
	}
	if len(result.Plan.Blockers) == 0 || result.Plan.Blockers[0].Code != ReasonUpgradeRequired {
		t.Fatalf("blockers=%+v", result.Plan.Blockers)
	}
	// Manual passes.
	result, err = PlanAliasMutateGate(cfg, "rev", "manual", "bind")
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("manual should pass: %+v", result.Plan.Blockers)
	}
}

func TestPlanDiscoveryUntrustedZeroAliasDiff(t *testing.T) {
	cfg := baseConfig()
	for _, status := range []string{DiscoverySkip, DiscoveryError, DiscoveryEmpty, DiscoveryIncomplete} {
		result, err := PlanDiscoveryReconcile(cfg, "rev", "p1", DiscoveryObservation{
			Status: status,
			Models: []string{"totally-new"},
		})
		if err != nil {
			t.Fatal(err)
		}
		if !result.Plan.Executable || !result.Plan.NoOp {
			t.Fatalf("status=%s plan=%+v", status, result.Plan)
		}
		if len(result.Candidate.Aliases) != len(cfg.Aliases) {
			t.Fatalf("status=%s mutated aliases", status)
		}
	}
}

func TestPlanDiscoveryTrustedPrunesOnlySystemTargets(t *testing.T) {
	cfg := baseConfig()
	result, err := PlanDiscoveryReconcile(cfg, "rev", "p1", DiscoveryObservation{
		Status: DiscoveryTrustedComplete,
		Models: []string{"other"}, // sys-model gone for p1
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("plan=%+v", result.Plan)
	}
	// sys-model: p1 system target removed, p2 remains
	idx, err := RequireUniqueAlias(result.Candidate, "sys-model")
	if err != nil {
		t.Fatal(err)
	}
	for _, tget := range result.Candidate.Aliases[idx].Targets {
		if tget.Provider == "p1" {
			t.Fatalf("system target for p1 retained: %+v", tget)
		}
	}
	// mixed: system a may be removed; protected b retained
	idx, err = RequireUniqueAlias(result.Candidate, "mixed")
	if err != nil {
		t.Fatal(err)
	}
	foundProtected := false
	for _, tget := range result.Candidate.Aliases[idx].Targets {
		if tget.Model == "a" && tget.Provider == "p1" {
			t.Fatal("system target a should be pruned")
		}
		if tget.Model == "b" {
			foundProtected = true
		}
	}
	if !foundProtected {
		t.Fatal("protected target b removed")
	}
	// locked untouched
	idx, err = RequireUniqueAlias(result.Candidate, "locked")
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Candidate.Aliases[idx].Targets) != 1 {
		t.Fatal("locked alias mutated")
	}
	// manual untouched
	idx, err = RequireUniqueAlias(result.Candidate, "manual")
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Candidate.Aliases[idx].Targets) != 1 {
		t.Fatal("manual alias mutated")
	}
}

func TestPlanProviderDisabledZeroAliasDiff(t *testing.T) {
	cfg := baseConfig()
	result, err := PlanProviderDisabled(cfg, "rev", "p1", true)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatal(result.Plan.Blockers)
	}
	if result.Candidate.FindProvider("p1") == nil || !result.Candidate.FindProvider("p1").Disabled {
		t.Fatal("disabled not applied")
	}
	if len(result.Candidate.Aliases) != len(cfg.Aliases) {
		t.Fatal("alias diff on disable")
	}
}

func TestCloneConfigDoesNotMutateBase(t *testing.T) {
	cfg := baseConfig()
	result, err := PlanProviderRemove(cfg, "rev", "p2", []Selection{
		// p2 only hits sys-model system target; no protected for p2 in fixture except none
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		// p2 is only on sys-model system targets — should be executable
		t.Fatalf("unexpected blockers: %+v choices=%+v", result.Plan.Blockers, result.Plan.Choices)
	}
	if cfg.FindProvider("p2") == nil {
		t.Fatal("base config was mutated")
	}
	if !strings.Contains(result.Plan.ContractVersion, "lifecycle") {
		t.Fatalf("contract=%s", result.Plan.ContractVersion)
	}
}

func multiGroupConfig() *config.Config {
	cfg := config.Default()
	cfg.Providers = []config.Provider{
		{
			ID:      "vendor",
			BaseURL: "https://vendor.example/v1",
			Groups: []config.ProviderGroup{
				{ID: "default", Protocol: config.ProtocolOpenAIResponses, Models: []string{"shared"}},
				{ID: "premium", Protocol: config.ProtocolOpenAIResponses, Models: []string{"shared", "premium-only"}},
			},
		},
	}
	cfg.Aliases = []config.Alias{
		{
			Alias: "shared", AutoGenerated: true, Enabled: true,
			Protocol: config.ProtocolOpenAIResponses,
			Targets: []config.Target{
				{Provider: "vendor", Group: "default", Model: "shared", Enabled: true, AutoGenerated: true},
				{Provider: "vendor", Group: "premium", Model: "shared", Enabled: true, AutoGenerated: true},
			},
		},
		{
			Alias: "manual-premium", Enabled: true,
			Protocol: config.ProtocolOpenAIResponses,
			Targets: []config.Target{
				{Provider: "vendor", Group: "premium", Model: "shared", Enabled: true},
			},
		},
		{
			Alias: "locked-premium", AutoGenerated: true, Locked: true, Enabled: true,
			Protocol: config.ProtocolOpenAIResponses,
			Targets: []config.Target{
				{Provider: "vendor", Group: "premium", Model: "premium-only", Enabled: true, AutoGenerated: true},
			},
		},
	}
	cfg.RequestRewriteRules = []config.RequestRewriteRule{
		{
			Name: "multi-groups", Alias: "shared", Enabled: true,
			ProviderGroups: []config.ProviderGroupSelector{
				{Provider: "vendor", Group: "default"},
				{Provider: "vendor", Group: "premium"},
			},
		},
		{
			Name: "premium-only", Alias: "shared", Enabled: true,
			ProviderGroups: []config.ProviderGroupSelector{
				{Provider: "vendor", Group: "premium"},
			},
		},
		{
			Name: "wild", Alias: "shared", Enabled: true,
			ProviderGroups: []config.ProviderGroupSelector{},
		},
	}
	return cfg
}

func TestPlanGroupRemoveSystemTargetsAndNarrowRewrite(t *testing.T) {
	cfg := multiGroupConfig()
	selections := []Selection{
		{ChoiceID: "protected_target:1:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "protected_target:2:0", OptionID: OptionDeleteAlias},
		{ChoiceID: "singleton_provider_groups:1", OptionID: OptionKeepDormant},
	}
	result, err := PlanGroupRemove(cfg, "rev", "vendor", "premium", selections)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("expected executable: blockers=%+v choices=%+v", result.Plan.Blockers, result.Plan.Choices)
	}
	if result.Candidate == nil {
		t.Fatal("missing candidate")
	}
	p := result.Candidate.FindProvider("vendor")
	if p == nil || len(p.Groups) != 1 || p.Groups[0].ID != "default" {
		t.Fatalf("groups after remove = %+v", p)
	}
	idx, err := RequireUniqueAlias(result.Candidate, "shared")
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Candidate.Aliases[idx].Targets) != 1 {
		t.Fatalf("shared targets=%+v", result.Candidate.Aliases[idx].Targets)
	}
	if result.Candidate.Aliases[idx].Targets[0].Group != "default" {
		t.Fatalf("shared remaining group=%q", result.Candidate.Aliases[idx].Targets[0].Group)
	}
	mi, err := RequireUniqueAlias(result.Candidate, "manual-premium")
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Candidate.Aliases[mi].Targets) != 0 {
		t.Fatalf("manual target should be removed: %+v", result.Candidate.Aliases[mi])
	}
	if _, err := RequireUniqueAlias(result.Candidate, "locked-premium"); err == nil {
		t.Fatal("locked alias should be deleted")
	}
	var multi *config.RequestRewriteRule
	for i := range result.Candidate.RequestRewriteRules {
		if result.Candidate.RequestRewriteRules[i].Name == "multi-groups" {
			multi = &result.Candidate.RequestRewriteRules[i]
		}
	}
	if multi == nil || len(multi.ProviderGroups) != 1 || multi.ProviderGroups[0].Group != "default" {
		t.Fatalf("multi rewrite not narrowed: %+v", multi)
	}
	var single *config.RequestRewriteRule
	for i := range result.Candidate.RequestRewriteRules {
		if result.Candidate.RequestRewriteRules[i].Name == "premium-only" {
			single = &result.Candidate.RequestRewriteRules[i]
		}
	}
	if single == nil || len(single.ProviderGroups) != 1 || single.ProviderGroups[0].Group != "premium" {
		t.Fatalf("singleton must stay dormant: %+v", single)
	}
	for _, rule := range result.Candidate.RequestRewriteRules {
		if rule.Name == "wild" && len(rule.ProviderGroups) != 0 {
			t.Fatalf("wildcard changed: %+v", rule)
		}
	}
}

func TestPlanGroupRemoveBlocksWithoutSelections(t *testing.T) {
	cfg := multiGroupConfig()
	result, err := PlanGroupRemove(cfg, "rev", "vendor", "premium", nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("protected targets and singleton rewrite must block")
	}
	if result.Candidate != nil {
		t.Fatal("candidate must be nil when not executable")
	}
	if len(result.Plan.Choices) == 0 {
		t.Fatal("expected required choices")
	}
}

func TestPlanGroupRemoveLastGroupBlocked(t *testing.T) {
	cfg := config.Default()
	cfg.Providers = []config.Provider{{
		ID: "only", BaseURL: "https://x.example/v1",
		Groups: []config.ProviderGroup{{ID: "default", Protocol: config.ProtocolOpenAIResponses}},
	}}
	result, err := PlanGroupRemove(cfg, "rev", "only", "default", nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("last group must be blocked")
	}
	found := false
	for _, b := range result.Plan.Blockers {
		if b.Code == ReasonLastGroup {
			found = true
		}
	}
	if !found {
		t.Fatalf("expected last_group blocker, got %+v", result.Plan.Blockers)
	}
}

func TestPlanGroupRemoveNeverSilentRebind(t *testing.T) {
	cfg := multiGroupConfig()
	result, err := PlanGroupRemove(cfg, "rev", "vendor", "premium", []Selection{
		{ChoiceID: "protected_target:1:0", OptionID: OptionRebindTarget, Params: map[string]any{
			"providerId": "vendor", "model": "shared",
		}},
		{ChoiceID: "protected_target:2:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "singleton_provider_groups:1", OptionID: OptionKeepDormant},
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("rebind without explicit groupId must not execute")
	}
	result, err = PlanGroupRemove(cfg, "rev", "vendor", "premium", []Selection{
		{ChoiceID: "protected_target:1:0", OptionID: OptionRebindTarget, Params: map[string]any{
			"providerId": "vendor", "groupId": "default", "model": "shared",
		}},
		{ChoiceID: "protected_target:2:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "singleton_provider_groups:1", OptionID: OptionKeepDormant},
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("explicit rebind should work: %+v", result.Plan.Blockers)
	}
	idx, err := RequireUniqueAlias(result.Candidate, "manual-premium")
	if err != nil {
		t.Fatal(err)
	}
	tget := result.Candidate.Aliases[idx].Targets[0]
	if tget.Group != "default" || tget.Provider != "vendor" || tget.AutoGenerated {
		t.Fatalf("rebind result=%+v", tget)
	}
}

func TestPlanGroupRemoveRejectsRebindDuplicateIdentity(t *testing.T) {
	t.Parallel()
	cfg := multiGroupConfig()
	for i := range cfg.Aliases {
		if cfg.Aliases[i].Alias == "manual-premium" {
			cfg.Aliases[i].Targets = append(cfg.Aliases[i].Targets, config.Target{
				Provider: "vendor", Group: "default", Model: "shared", Enabled: true,
			})
		}
	}
	result, err := PlanGroupRemove(cfg, "rev", "vendor", "premium", []Selection{
		{ChoiceID: "protected_target:1:0", OptionID: OptionRebindTarget, Params: map[string]any{
			"providerId": "vendor", "groupId": "default", "model": "shared",
		}},
		{ChoiceID: "protected_target:2:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "singleton_provider_groups:1", OptionID: OptionKeepDormant},
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable || len(result.Plan.Blockers) == 0 {
		t.Fatalf("duplicate rebind should be blocked: %+v", result.Plan)
	}
}

func TestPlanGroupRemoveMissingEntities(t *testing.T) {
	cfg := multiGroupConfig()
	result, err := PlanGroupRemove(cfg, "rev", "missing", "premium", nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable || len(result.Plan.Blockers) == 0 || result.Plan.Blockers[0].Code != ReasonProviderMissing {
		t.Fatalf("provider missing: %+v", result.Plan)
	}
	result, err = PlanGroupRemove(cfg, "rev", "vendor", "nope", nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable || len(result.Plan.Blockers) == 0 || result.Plan.Blockers[0].Code != ReasonGroupMissing {
		t.Fatalf("group missing: %+v", result.Plan)
	}
}

func TestPlanGroupIDChangeAtomicRename(t *testing.T) {
	cfg := multiGroupConfig()
	result, err := PlanGroupIDChange(cfg, "rev", "vendor", "premium", "gold", nil)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("plan=%+v", result.Plan)
	}
	p := result.Candidate.FindProvider("vendor")
	if p == nil {
		t.Fatal("provider missing")
	}
	ids := map[string]bool{}
	for _, g := range p.Groups {
		ids[g.ID] = true
	}
	if !ids["default"] || !ids["gold"] || ids["premium"] {
		t.Fatalf("group ids=%v", ids)
	}
	idx, err := RequireUniqueAlias(result.Candidate, "shared")
	if err != nil {
		t.Fatal(err)
	}
	for _, tget := range result.Candidate.Aliases[idx].Targets {
		if tget.Group == "premium" {
			t.Fatal("premium target not renamed")
		}
		if tget.Group == "gold" && !tget.AutoGenerated {
			t.Fatal("auto flag cleared on rename")
		}
		if tget.Group == "default" && !tget.AutoGenerated {
			t.Fatal("default target ownership changed")
		}
	}
	for _, rule := range result.Candidate.RequestRewriteRules {
		for _, sel := range rule.ProviderGroups {
			if sel.Group == "premium" {
				t.Fatalf("selector not renamed in %s: %+v", rule.Name, sel)
			}
		}
	}
	if cfg.FindProvider("vendor").FindGroup("premium") == nil {
		t.Fatal("base mutated")
	}
}

func TestPlanGroupIDChangeConflictAndMissing(t *testing.T) {
	cfg := multiGroupConfig()
	// Destination group already exists → must block (never silent overwrite).
	result, err := PlanGroupIDChange(cfg, "rev", "vendor", "premium", "default", nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("conflict with existing id must block")
	}
	found := false
	for _, b := range result.Plan.Blockers {
		if b.Code == ReasonGroupIDConflict {
			found = true
		}
	}
	if !found {
		t.Fatalf("blockers=%+v", result.Plan.Blockers)
	}

	// Existing destination still blocks even if dangling refs already point at it.
	idx, err := RequireUniqueAlias(cfg, "shared")
	if err != nil {
		t.Fatal(err)
	}
	cfg.Aliases[idx].Targets = append(cfg.Aliases[idx].Targets, config.Target{
		Provider: "vendor", Group: "default", Model: "premium-only", Enabled: true, AutoGenerated: true,
	})
	result, err = PlanGroupIDChange(cfg, "rev", "vendor", "premium", "default", nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("existing destination group must block even with dangling/colliding refs")
	}
	found = false
	for _, b := range result.Plan.Blockers {
		if b.Code == ReasonGroupIDConflict {
			found = true
		}
	}
	if !found {
		t.Fatalf("expected group_id_conflict with dangling refs present, blockers=%+v", result.Plan.Blockers)
	}

	result, err = PlanGroupIDChange(cfg, "rev", "vendor", "premium", "premium", nil)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable || !result.Plan.NoOp {
		t.Fatalf("same id should be no-op: %+v", result.Plan)
	}
}

func TestPlanGroupIDChangeDedupesCollidingTargetsAndSelectors(t *testing.T) {
	cfg := multiGroupConfig()
	// Dangling identities only: alias target + rewrite selector already reference
	// "gold", but no gold provider group exists yet. Renaming premium→gold must
	// execute and safely dedupe, not create duplicate identities.
	// Prefer the routable old target's Enabled/AutoGenerated over dangling properties.
	// (If a real gold group existed, that is a destination conflict — see Conflict test.)
	if p := cfg.FindProvider("vendor"); p == nil || p.FindGroup("gold") != nil {
		t.Fatal("fixture requires vendor without destination group gold")
	}

	idx, err := RequireUniqueAlias(cfg, "shared")
	if err != nil {
		t.Fatal(err)
	}
	// Mark old premium target with distinctive props so we can prove they survive.
	for ti := range cfg.Aliases[idx].Targets {
		tget := &cfg.Aliases[idx].Targets[ti]
		if tget.Group == "premium" && tget.Model == "shared" {
			tget.Enabled = false
			tget.AutoGenerated = false
		}
	}
	// shared already has default+premium; add dangling gold for same model with opposite props.
	cfg.Aliases[idx].Targets = append(cfg.Aliases[idx].Targets, config.Target{
		Provider: "vendor", Group: "gold", Model: "shared", Enabled: true, AutoGenerated: true,
	})
	// multi-groups has default+premium; add dangling gold so premium→gold collides.
	for i := range cfg.RequestRewriteRules {
		if cfg.RequestRewriteRules[i].Name == "multi-groups" {
			cfg.RequestRewriteRules[i].ProviderGroups = append(cfg.RequestRewriteRules[i].ProviderGroups,
				config.ProviderGroupSelector{Provider: "vendor", Group: "gold"},
			)
		}
	}

	result, err := PlanGroupIDChange(cfg, "rev", "vendor", "premium", "gold", nil)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("plan should execute with dangling-identity dedupe: blockers=%+v", result.Plan.Blockers)
	}
	dedupeTarget := false
	dedupeRewrite := false
	retargetOld := false
	for _, ch := range result.Plan.AutomaticChanges {
		if action, _ := ch.Params["action"].(string); action == "dedupe_collision" {
			if ch.Entity == EntityAliasTarget {
				dedupeTarget = true
			}
			if ch.Entity == EntityRewriteRule {
				dedupeRewrite = true
			}
		}
		if ch.Entity == EntityAliasTarget && ch.Kind == ChangeUpdate {
			if oldG, _ := ch.Params["oldGroupId"].(string); oldG == "premium" {
				retargetOld = true
			}
		}
	}
	if !dedupeTarget {
		t.Fatalf("expected dangling target remove automatic change, got %+v", result.Plan.AutomaticChanges)
	}
	if !dedupeRewrite {
		t.Fatalf("expected rewrite selector dedupe automatic change, got %+v", result.Plan.AutomaticChanges)
	}
	if !retargetOld {
		t.Fatalf("expected old target retarget automatic change, got %+v", result.Plan.AutomaticChanges)
	}

	// Candidate: premium renamed to gold; only one shared target at gold; multi-groups unique gold once.
	p := result.Candidate.FindProvider("vendor")
	if p == nil || p.FindGroup("premium") != nil || p.FindGroup("gold") == nil {
		t.Fatalf("expected premium→gold rename on groups, got %+v", p)
	}
	aidx, err := RequireUniqueAlias(result.Candidate, "shared")
	if err != nil {
		t.Fatal(err)
	}
	goldCount := 0
	var goldTarget *config.Target
	for i := range result.Candidate.Aliases[aidx].Targets {
		tget := &result.Candidate.Aliases[aidx].Targets[i]
		if tget.Group == "premium" {
			t.Fatal("premium target should be gone")
		}
		if tget.Provider == "vendor" && tget.Group == "gold" && tget.Model == "shared" {
			goldCount++
			goldTarget = tget
		}
	}
	if goldCount != 1 {
		t.Fatalf("gold shared targets = %d, want 1; targets=%+v", goldCount, result.Candidate.Aliases[aidx].Targets)
	}
	// Must keep routable old properties, not dangling Enabled/AutoGenerated.
	if goldTarget == nil || goldTarget.Enabled || goldTarget.AutoGenerated {
		t.Fatalf("gold target must preserve old props (Enabled=false, AutoGenerated=false), got %+v", goldTarget)
	}
	for _, rule := range result.Candidate.RequestRewriteRules {
		if rule.Name != "multi-groups" {
			continue
		}
		seen := map[string]int{}
		for _, sel := range rule.ProviderGroups {
			seen[sel.Provider+"/"+sel.Group]++
		}
		if seen["vendor/gold"] != 1 {
			t.Fatalf("multi-groups selectors not deduped: %+v", rule.ProviderGroups)
		}
		if seen["vendor/premium"] != 0 {
			t.Fatalf("premium selector remained: %+v", rule.ProviderGroups)
		}
	}
}

func TestPlanGroupRemoveDuplicateTargetsByIndex(t *testing.T) {
	// Two protected targets share the same (alias, provider, group, model) identity
	// but live at different targetIndex values. Selections must apply by index so
	// remove and rebind do not overwrite each other.
	cfg := config.Default()
	cfg.Providers = []config.Provider{{
		ID: "vendor", BaseURL: "https://vendor.example/v1",
		Groups: []config.ProviderGroup{
			{ID: "default", Protocol: config.ProtocolOpenAIResponses, Models: []string{"shared"}},
			{ID: "premium", Protocol: config.ProtocolOpenAIResponses, Models: []string{"shared"}},
		},
	}}
	cfg.Aliases = []config.Alias{{
		Alias: "dup", Enabled: true,
		Protocol: config.ProtocolOpenAIResponses,
		Targets: []config.Target{
			{Provider: "vendor", Group: "premium", Model: "shared", Enabled: true},
			{Provider: "vendor", Group: "premium", Model: "shared", Enabled: false},
		},
	}}
	cfg.RequestRewriteRules = nil

	result, err := PlanGroupRemove(cfg, "rev", "vendor", "premium", []Selection{
		{ChoiceID: "protected_target:0:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "protected_target:0:1", OptionID: OptionRebindTarget, Params: map[string]any{
			"providerId": "vendor", "groupId": "default", "model": "shared",
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("expected executable with per-index selections: blockers=%+v choices=%+v", result.Plan.Blockers, result.Plan.Choices)
	}
	if len(result.Plan.Choices) != 2 {
		t.Fatalf("want 2 precise choices, got %+v", result.Plan.Choices)
	}
	for _, c := range result.Plan.Choices {
		if c.ID != "protected_target:0:0" && c.ID != "protected_target:0:1" {
			t.Fatalf("choice id must be aliasIndex:targetIndex precise, got %q", c.ID)
		}
	}
	aidx, err := RequireUniqueAlias(result.Candidate, "dup")
	if err != nil {
		t.Fatal(err)
	}
	targets := result.Candidate.Aliases[aidx].Targets
	if len(targets) != 1 {
		t.Fatalf("want 1 remaining target after remove+rebind, got %+v", targets)
	}
	// Only targetIndex 1 survives, rebound to default, preserving original Enabled=false.
	if targets[0].Group != "default" || targets[0].Model != "shared" || targets[0].Enabled {
		t.Fatalf("rebind must act on targetIndex 1 only: %+v", targets[0])
	}
	if targets[0].AutoGenerated {
		t.Fatal("rebind must clear AutoGenerated")
	}
}

func TestPlanGroupRemoveReplaceProviderGroupsValidation(t *testing.T) {
	cfg := multiGroupConfig()
	// Missing provider/group → invalid_selection blocker.
	result, err := PlanGroupRemove(cfg, "rev", "vendor", "premium", []Selection{
		{ChoiceID: "protected_target:1:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "protected_target:2:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "singleton_provider_groups:1", OptionID: OptionReplaceProviderGroups, Params: map[string]any{
			"providerGroups": []any{
				map[string]any{"provider": "vendor", "group": "nope"},
			},
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("missing group must block replace_provider_groups")
	}
	foundInvalid := false
	for _, b := range result.Plan.Blockers {
		if b.Code == ReasonInvalidSelection {
			foundInvalid = true
		}
	}
	if !foundInvalid {
		t.Fatalf("expected invalid_selection blocker, got %+v", result.Plan.Blockers)
	}

	// Must not include the group being removed.
	result, err = PlanGroupRemove(cfg, "rev", "vendor", "premium", []Selection{
		{ChoiceID: "protected_target:1:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "protected_target:2:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "singleton_provider_groups:1", OptionID: OptionReplaceProviderGroups, Params: map[string]any{
			"providerGroups": []any{
				map[string]any{"provider": "vendor", "group": "premium"},
			},
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("replace must not accept the group being removed")
	}

	// Dedupe + valid surviving group should execute once.
	result, err = PlanGroupRemove(cfg, "rev", "vendor", "premium", []Selection{
		{ChoiceID: "protected_target:1:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "protected_target:2:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "singleton_provider_groups:1", OptionID: OptionReplaceProviderGroups, Params: map[string]any{
			"providerGroups": []any{
				map[string]any{"provider": "vendor", "group": "default"},
				map[string]any{"provider": "vendor", "group": "default"},
			},
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("deduped valid replace should execute: blockers=%+v", result.Plan.Blockers)
	}
	var premiumOnly *config.RequestRewriteRule
	for i := range result.Candidate.RequestRewriteRules {
		if result.Candidate.RequestRewriteRules[i].Name == "premium-only" {
			premiumOnly = &result.Candidate.RequestRewriteRules[i]
		}
	}
	if premiumOnly == nil || len(premiumOnly.ProviderGroups) != 1 ||
		premiumOnly.ProviderGroups[0].Provider != "vendor" || premiumOnly.ProviderGroups[0].Group != "default" {
		t.Fatalf("deduped replace result=%+v", premiumOnly)
	}
}

func TestPlanGroupRemoveReplaceProviderGroupsWithParams(t *testing.T) {
	cfg := multiGroupConfig()
	result, err := PlanGroupRemove(cfg, "rev", "vendor", "premium", []Selection{
		{ChoiceID: "protected_target:1:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "protected_target:2:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "singleton_provider_groups:1", OptionID: OptionReplaceProviderGroups, Params: map[string]any{
			"providerGroups": []any{
				map[string]any{"provider": "vendor", "group": "default"},
			},
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("replace_provider_groups should execute: blockers=%+v choices=%+v", result.Plan.Blockers, result.Plan.Choices)
	}
	var premiumOnly *config.RequestRewriteRule
	for i := range result.Candidate.RequestRewriteRules {
		if result.Candidate.RequestRewriteRules[i].Name == "premium-only" {
			premiumOnly = &result.Candidate.RequestRewriteRules[i]
		}
	}
	if premiumOnly == nil || len(premiumOnly.ProviderGroups) != 1 ||
		premiumOnly.ProviderGroups[0].Provider != "vendor" || premiumOnly.ProviderGroups[0].Group != "default" {
		t.Fatalf("premium-only not replaced: %+v", premiumOnly)
	}
}

func TestPlanOperationDispatchesGroupOps(t *testing.T) {
	cfg := multiGroupConfig()
	rawRemove, _ := json.Marshal(GroupRemovePayload{ProviderID: "vendor", GroupID: "premium"})
	result, err := PlanOperation(cfg, "rev", Operation{Kind: OpGroupRemove, Payload: rawRemove}, []Selection{
		{ChoiceID: "protected_target:1:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "protected_target:2:0", OptionID: OptionRemoveTarget},
		{ChoiceID: "singleton_provider_groups:1", OptionID: OptionDeleteRule},
	}, ExternalRefs{})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable || result.Plan.OperationKind != OpGroupRemove {
		t.Fatalf("group remove dispatch failed: %+v", result.Plan)
	}
	for _, rule := range result.Candidate.RequestRewriteRules {
		if rule.Name == "premium-only" {
			t.Fatal("premium-only rule should be deleted")
		}
	}

	rawRename, _ := json.Marshal(GroupIDChangePayload{ProviderID: "vendor", OldGroupID: "premium", NewGroupID: "lane-b"})
	result, err = PlanOperation(cfg, "rev", Operation{Kind: OpGroupIDChange, Payload: rawRename}, nil, ExternalRefs{})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable || result.Plan.OperationKind != OpGroupIDChange {
		t.Fatalf("group id change dispatch failed: %+v", result.Plan)
	}
	if result.Candidate.FindProvider("vendor").FindGroup("lane-b") == nil {
		t.Fatal("rename via PlanOperation failed")
	}
}
