package lifecycle

import (
	"strings"
	"testing"

	"github.com/Apale7/opencode-provider-switch/internal/config"
)

func baseConfig() *config.Config {
	cfg := config.Default()
	cfg.Providers = []config.Provider{
		{ID: "p1", BaseURL: "https://p1.example/v1"},
		{ID: "p2", BaseURL: "https://p2.example/v1"},
	}
	cfg.ProviderPriority = []string{"p1", "p2"}
	cfg.Aliases = []config.Alias{
		{
			Alias: "sys-model", AutoGenerated: true, Enabled: true,
			Targets: []config.Target{
				{Provider: "p1", Model: "sys-model", Enabled: true, AutoGenerated: true},
				{Provider: "p2", Model: "sys-model", Enabled: true, AutoGenerated: true},
			},
		},
		{
			Alias: "manual", Enabled: true,
			Targets: []config.Target{{Provider: "p1", Model: "m", Enabled: true}},
		},
		{
			Alias: "mixed", AutoGenerated: true, Enabled: true,
			Targets: []config.Target{
				{Provider: "p1", Model: "a", Enabled: true, AutoGenerated: true},
				{Provider: "p1", Model: "b", Enabled: true, AutoGenerated: false},
			},
		},
		{
			Alias: "locked", AutoGenerated: true, Locked: true, Enabled: true,
			Targets: []config.Target{{Provider: "p1", Model: "L", Enabled: true, AutoGenerated: true}},
		},
	}
	cfg.RequestRewriteRules = []config.RequestRewriteRule{
		{Name: "multi", Alias: "manual", Providers: []string{"p1", "p2"}, Enabled: true},
		{Name: "single", Alias: "manual", Providers: []string{"p1"}, Enabled: true},
		{Name: "wild", Alias: "other", Providers: nil, Enabled: true},
	}
	return cfg
}

func TestPlanProviderRemoveSystemAndPriorityAndNarrow(t *testing.T) {
	cfg := baseConfig()
	// Resolve protected targets and singleton rewrite.
	selections := []Selection{
		{ChoiceID: "protected_target:1:0", OptionID: OptionRemoveTarget}, // manual
		{ChoiceID: "protected_target:2:1", OptionID: OptionRemoveTarget}, // mixed protected b
		{ChoiceID: "protected_target:3:0", OptionID: OptionDeleteAlias},  // locked
		{ChoiceID: "singleton_rewrite:1", OptionID: OptionKeepDormant},
	}
	result, err := PlanProviderRemove(cfg, "rev-base", "p1", selections)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("expected executable plan, got blockers=%+v choices=%+v", result.Plan.Blockers, result.Plan.Choices)
	}
	if result.Candidate == nil {
		t.Fatal("missing candidate")
	}
	if result.Candidate.FindProvider("p1") != nil {
		t.Fatal("provider p1 still present")
	}
	for _, id := range result.Candidate.ProviderPriority {
		if id == "p1" {
			t.Fatal("priority retained p1")
		}
	}
	// multi rewrite narrowed to [p2]
	var multi *config.RequestRewriteRule
	for i := range result.Candidate.RequestRewriteRules {
		if result.Candidate.RequestRewriteRules[i].Name == "multi" {
			multi = &result.Candidate.RequestRewriteRules[i]
		}
	}
	if multi == nil || len(multi.Providers) != 1 || multi.Providers[0] != "p2" {
		t.Fatalf("multi rewrite not narrowed: %+v", multi)
	}
	// singleton kept dormant with p1
	var single *config.RequestRewriteRule
	for i := range result.Candidate.RequestRewriteRules {
		if result.Candidate.RequestRewriteRules[i].Name == "single" {
			single = &result.Candidate.RequestRewriteRules[i]
		}
	}
	if single == nil || len(single.Providers) != 1 || single.Providers[0] != "p1" {
		t.Fatalf("singleton must stay dormant, got %+v", single)
	}
	// wildcard unchanged
	for _, rule := range result.Candidate.RequestRewriteRules {
		if rule.Name == "wild" && len(rule.Providers) != 0 {
			t.Fatalf("wildcard changed: %+v", rule)
		}
	}
	// locked alias deleted via selection
	if idx, _ := RequireUniqueAlias(result.Candidate, "locked"); idx >= 0 {
		t.Fatal("locked alias should be deleted by selection")
	}
	// pure auto sys-model still has p2 target
	idx, err := RequireUniqueAlias(result.Candidate, "sys-model")
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Candidate.Aliases[idx].Targets) != 1 || result.Candidate.Aliases[idx].Targets[0].Provider != "p2" {
		t.Fatalf("sys-model targets=%+v", result.Candidate.Aliases[idx].Targets)
	}
}

func TestPlanProviderRemoveBlocksWithoutSelections(t *testing.T) {
	cfg := baseConfig()
	result, err := PlanProviderRemove(cfg, "rev", "p1", nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("protected targets must block execute")
	}
	if result.Candidate != nil {
		t.Fatal("candidate must be nil when not executable")
	}
	if len(result.Plan.Choices) == 0 {
		t.Fatal("expected required choices")
	}
}

func TestPlanProviderRemoveNeverExpandsSingletonToWildcard(t *testing.T) {
	cfg := config.Default()
	cfg.Providers = []config.Provider{{ID: "only", BaseURL: "https://x.example/v1"}}
	cfg.RequestRewriteRules = []config.RequestRewriteRule{
		{Name: "s", Alias: "a", Providers: []string{"only"}, Enabled: true},
	}
	result, err := PlanProviderRemove(cfg, "rev", "only", nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("singleton rewrite must require choice")
	}
	found := false
	for _, c := range result.Plan.Choices {
		if c.Code == ReasonSingletonRewrite {
			found = true
			for _, opt := range c.Options {
				if opt.ID == OptionKeepDormant || opt.ID == OptionDisableRule || opt.ID == OptionDeleteRule || opt.ID == OptionReplaceProviders {
					continue
				}
				t.Fatalf("unexpected option %q", opt.ID)
			}
		}
	}
	if !found {
		t.Fatal("missing singleton rewrite choice")
	}
	// Automatic changes must not include rewriting singleton to empty.
	for _, ch := range result.Plan.AutomaticChanges {
		if ch.ReasonCode == ReasonRewriteSelectorNarrow {
			t.Fatalf("singleton must not be auto-narrowed: %+v", ch)
		}
	}
}

func TestPlanProviderRemoveEmptyPureAutoAlias(t *testing.T) {
	cfg := config.Default()
	cfg.Providers = []config.Provider{{ID: "p1", BaseURL: "https://x.example/v1"}}
	cfg.Aliases = []config.Alias{{
		Alias: "only-sys", AutoGenerated: true, Enabled: true,
		Targets: []config.Target{{Provider: "p1", Model: "only-sys", Enabled: true, AutoGenerated: true}},
	}}
	result, err := PlanProviderRemove(cfg, "rev", "p1", nil)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("should be executable: %+v", result.Plan.Blockers)
	}
	if len(result.Candidate.Aliases) != 0 {
		t.Fatalf("empty pure auto alias retained: %+v", result.Candidate.Aliases)
	}
}

func TestPlanAliasRemoveKeepsRewriteByDefaultChoice(t *testing.T) {
	cfg := baseConfig()
	// Alias manual is referenced by multi+single rewrite rules.
	selections := []Selection{
		{ChoiceID: "rewrite_on_alias_remove:0", OptionID: OptionKeepRule},
		{ChoiceID: "rewrite_on_alias_remove:1", OptionID: OptionDisableRule},
	}
	result, err := PlanAliasRemove(cfg, "rev", "manual", selections, ExternalRefs{
		OpenCodeModel: "manual",
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("plan=%+v", result.Plan)
	}
	if _, err := RequireUniqueAlias(result.Candidate, "manual"); err == nil {
		t.Fatal("alias should be removed")
	}
	var multi, single *config.RequestRewriteRule
	for i := range result.Candidate.RequestRewriteRules {
		r := &result.Candidate.RequestRewriteRules[i]
		switch r.Name {
		case "multi":
			multi = r
		case "single":
			single = r
		}
	}
	if multi == nil || multi.Alias != "manual" {
		t.Fatalf("keep rule lost: %+v", multi)
	}
	if single == nil || single.Enabled {
		t.Fatalf("disable rule failed: %+v", single)
	}
	foundOpenCode := false
	for _, issue := range result.Plan.PreservedIssues {
		if issue.Code == ReasonOpenCodeWeakRef {
			foundOpenCode = true
		}
		if issue.Code == ReasonDirectFallbackPossible {
			if v, _ := issue.Params["directFallbackPossible"].(bool); !v {
				t.Fatal("direct fallback flag missing")
			}
		}
	}
	if !foundOpenCode {
		t.Fatal("expected opencode weak ref preserved issue")
	}
}

func TestPlanAliasUpgradeOnlyOwnershipFlags(t *testing.T) {
	cfg := baseConfig()
	before := cfg.Aliases[0]
	result, err := PlanAliasUpgrade(cfg, "rev", "sys-model")
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable || result.Plan.NoOp {
		t.Fatalf("plan=%+v", result.Plan)
	}
	idx, err := RequireUniqueAlias(result.Candidate, "sys-model")
	if err != nil {
		t.Fatal(err)
	}
	after := result.Candidate.Aliases[idx]
	if after.AutoGenerated || after.Locked {
		t.Fatalf("ownership not cleared: %+v", after)
	}
	if after.Alias != before.Alias || after.Enabled != before.Enabled || len(after.Targets) != len(before.Targets) {
		t.Fatalf("non-ownership fields changed: before=%+v after=%+v", before, after)
	}
	for i := range after.Targets {
		if after.Targets[i].AutoGenerated {
			t.Fatal("target ownership not cleared")
		}
		if after.Targets[i].Provider != before.Targets[i].Provider || after.Targets[i].Model != before.Targets[i].Model {
			t.Fatal("target identity changed")
		}
	}
}

func TestPlanAliasMutateGateRejectsAuto(t *testing.T) {
	cfg := baseConfig()
	result, err := PlanAliasMutateGate(cfg, "rev", "sys-model", "bind")
	if err != nil {
		t.Fatal(err)
	}
	if result.Plan.Executable {
		t.Fatal("auto alias mutation must be blocked")
	}
	if len(result.Plan.Blockers) == 0 || result.Plan.Blockers[0].Code != ReasonUpgradeRequired {
		t.Fatalf("blockers=%+v", result.Plan.Blockers)
	}
	// Manual passes.
	result, err = PlanAliasMutateGate(cfg, "rev", "manual", "bind")
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("manual should pass: %+v", result.Plan.Blockers)
	}
}

func TestPlanDiscoveryUntrustedZeroAliasDiff(t *testing.T) {
	cfg := baseConfig()
	for _, status := range []string{DiscoverySkip, DiscoveryError, DiscoveryEmpty, DiscoveryIncomplete} {
		result, err := PlanDiscoveryReconcile(cfg, "rev", "p1", DiscoveryObservation{
			Status: status,
			Models: []string{"totally-new"},
		})
		if err != nil {
			t.Fatal(err)
		}
		if !result.Plan.Executable || !result.Plan.NoOp {
			t.Fatalf("status=%s plan=%+v", status, result.Plan)
		}
		if len(result.Candidate.Aliases) != len(cfg.Aliases) {
			t.Fatalf("status=%s mutated aliases", status)
		}
	}
}

func TestPlanDiscoveryTrustedPrunesOnlySystemTargets(t *testing.T) {
	cfg := baseConfig()
	result, err := PlanDiscoveryReconcile(cfg, "rev", "p1", DiscoveryObservation{
		Status: DiscoveryTrustedComplete,
		Models: []string{"other"}, // sys-model gone for p1
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatalf("plan=%+v", result.Plan)
	}
	// sys-model: p1 system target removed, p2 remains
	idx, err := RequireUniqueAlias(result.Candidate, "sys-model")
	if err != nil {
		t.Fatal(err)
	}
	for _, tget := range result.Candidate.Aliases[idx].Targets {
		if tget.Provider == "p1" {
			t.Fatalf("system target for p1 retained: %+v", tget)
		}
	}
	// mixed: system a may be removed; protected b retained
	idx, err = RequireUniqueAlias(result.Candidate, "mixed")
	if err != nil {
		t.Fatal(err)
	}
	foundProtected := false
	for _, tget := range result.Candidate.Aliases[idx].Targets {
		if tget.Model == "a" && tget.Provider == "p1" {
			t.Fatal("system target a should be pruned")
		}
		if tget.Model == "b" {
			foundProtected = true
		}
	}
	if !foundProtected {
		t.Fatal("protected target b removed")
	}
	// locked untouched
	idx, err = RequireUniqueAlias(result.Candidate, "locked")
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Candidate.Aliases[idx].Targets) != 1 {
		t.Fatal("locked alias mutated")
	}
	// manual untouched
	idx, err = RequireUniqueAlias(result.Candidate, "manual")
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Candidate.Aliases[idx].Targets) != 1 {
		t.Fatal("manual alias mutated")
	}
}

func TestPlanProviderDisabledZeroAliasDiff(t *testing.T) {
	cfg := baseConfig()
	result, err := PlanProviderDisabled(cfg, "rev", "p1", true)
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		t.Fatal(result.Plan.Blockers)
	}
	if result.Candidate.FindProvider("p1") == nil || !result.Candidate.FindProvider("p1").Disabled {
		t.Fatal("disabled not applied")
	}
	if len(result.Candidate.Aliases) != len(cfg.Aliases) {
		t.Fatal("alias diff on disable")
	}
}

func TestCloneConfigDoesNotMutateBase(t *testing.T) {
	cfg := baseConfig()
	result, err := PlanProviderRemove(cfg, "rev", "p2", []Selection{
		// p2 only hits sys-model system target; no protected for p2 in fixture except none
	})
	if err != nil {
		t.Fatal(err)
	}
	if !result.Plan.Executable {
		// p2 is only on sys-model system targets — should be executable
		t.Fatalf("unexpected blockers: %+v choices=%+v", result.Plan.Blockers, result.Plan.Choices)
	}
	if cfg.FindProvider("p2") == nil {
		t.Fatal("base config was mutated")
	}
	if !strings.Contains(result.Plan.ContractVersion, "lifecycle") {
		t.Fatalf("contract=%s", result.Plan.ContractVersion)
	}
}
