package lifecycle

import (
	"fmt"
	"strings"

	"github.com/Apale7/opencode-provider-switch/internal/config"
)

// AliasOwnership classifies an alias for lifecycle decisions.
type AliasOwnership string

const (
	OwnershipManual    AliasOwnership = "manual"
	OwnershipLocked    AliasOwnership = "locked_auto"
	OwnershipUnlocked  AliasOwnership = "unlocked_auto"
	OwnershipMixed     AliasOwnership = "historical_mixed"
	OwnershipAmbiguous AliasOwnership = "ambiguous"
)

// ClassifyAlias returns ownership for one alias occurrence.
// Parent protection wins over target provenance.
func ClassifyAlias(alias config.Alias) AliasOwnership {
	if !alias.AutoGenerated {
		return OwnershipManual
	}
	if alias.Locked {
		return OwnershipLocked
	}
	hasSystem, hasProtected := false, false
	for _, t := range alias.Targets {
		if t.AutoGenerated {
			hasSystem = true
		} else {
			hasProtected = true
		}
	}
	if hasProtected && hasSystem {
		return OwnershipMixed
	}
	if hasProtected {
		return OwnershipMixed
	}
	return OwnershipUnlocked
}

// TargetSystemOwned reports whether a target may be auto-maintained.
func TargetSystemOwned(alias config.Alias, target config.Target) bool {
	return alias.AutoGenerated && !alias.Locked && target.AutoGenerated
}

// TargetProtected reports whether a target requires explicit choice on provider remove.
func TargetProtected(alias config.Alias, target config.Target) bool {
	if !alias.AutoGenerated || alias.Locked {
		return true
	}
	return !target.AutoGenerated
}

// FindAliasesByName returns all alias indexes with the given name.
func FindAliasesByName(cfg *config.Config, name string) []int {
	name = strings.TrimSpace(name)
	var out []int
	for i, alias := range cfg.Aliases {
		if alias.Alias == name {
			out = append(out, i)
		}
	}
	return out
}

// RequireUniqueAlias returns the single alias index or an ownership/ambiguity error.
func RequireUniqueAlias(cfg *config.Config, name string) (int, error) {
	indexes := FindAliasesByName(cfg, name)
	switch len(indexes) {
	case 0:
		return -1, fmt.Errorf("%s: alias %q not found", ReasonAliasMissing, name)
	case 1:
		return indexes[0], nil
	default:
		return -1, fmt.Errorf("%s: alias %q is ambiguous", ReasonAliasAmbiguous, name)
	}
}

// RequireManualAliasMutation validates that an alias exists before a candidate
// mutation.
//
// Deprecated: automatic model aliases are editable overlays; new callers should
// use RequireUniqueAlias directly and apply operation-specific checks.
func RequireManualAliasMutation(cfg *config.Config, name string) error {
	_, err := RequireUniqueAlias(cfg, name)
	return err
}

// PureAutoAlias reports whether every target is system-owned under an unlocked auto alias.
func PureAutoAlias(alias config.Alias) bool {
	if !alias.AutoGenerated || alias.Locked {
		return false
	}
	if len(alias.Targets) == 0 {
		return true
	}
	for _, t := range alias.Targets {
		if !t.AutoGenerated {
			return false
		}
	}
	return true
}
