package cli

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Apale7/opencode-provider-switch/internal/app"
	"github.com/Apale7/opencode-provider-switch/internal/config"
	"github.com/Apale7/opencode-provider-switch/internal/lifecycle"
)

func newAliasCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "alias",
		Short: "Manage logical aliases routed by ocswitch",
		Long: `Alias commands manage the user-facing model names that OpenCode sees as
ocswitch/<alias>.

Each alias contains an ordered target chain of provider/model pairs. Target
order is operational: ocswitch tries targets in order and only fails over before any
response bytes are sent downstream.

Common workflow: create an alias, bind primary and fallback targets, inspect the
result with alias list, then run doctor and opencode sync.`,
		Example: `  ocswitch alias add --name gpt-5.4 --display-name "GPT 5.4"
	  ocswitch alias bind --alias gpt-5.4 --model su8/gpt-5.4
	  ocswitch alias bind --alias gpt-5.4 --model codex/GPT-5.4
	  ocswitch alias list`,
	}
	c.AddCommand(newAliasAddCmd(), newAliasListCmd(), newAliasBindCmd(), newAliasUnbindCmd(), newAliasResetOrderCmd(), newAliasRemoveCmd())
	return c
}

func newAliasAddCmd() *cobra.Command {
	var name, display, protocol string
	var disabled bool
	var dryRun bool
	cmd := &cobra.Command{
		Use:   "add",
		Short: "Create or update an alias (without targets)",
		Long: `alias add creates or updates alias metadata in local ocswitch config via Service.

It writes alias metadata only; targets are managed with alias bind/unbind.
Automatic model aliases can be edited directly as user overrides and remain
catalog-maintained.

When updating an existing alias, omitted display-name preserves the current
value and existing targets stay attached. Typical next step: add targets with
ocswitch alias bind.`,
		Example: `  ocswitch alias add --name gpt-5.4 --display-name "GPT 5.4"
  ocswitch alias add --name gpt-5.4-mini --disabled
  ocswitch alias add --name gpt-5.4 --display-name "GPT 5.4 Reasoning"`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if name == "" {
				return fmt.Errorf("--name is required")
			}
			if dryRun {
				fmt.Fprintf(cmd.OutOrStdout(), "dry-run: would upsert alias %q via Service/ConfigStore\n", name)
				return nil
			}
			view, err := appService().UpsertAlias(cmd.Context(), app.AliasUpsertInput{
				Alias:       name,
				DisplayName: display,
				Protocol:    protocol,
				Disabled:    disabled,
			})
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "saved alias %q [%s] (enabled=%v)\n", view.Alias, view.Protocol, view.Enabled)
			return nil
		},
	}
	cmd.Flags().StringVar(&name, "name", "", "alias name exposed as ocswitch/<name> in OpenCode (required)")
	cmd.Flags().StringVar(&display, "display-name", "", "human-friendly display name")
	cmd.Flags().StringVar(&protocol, "protocol", config.ProtocolOpenAIResponses, "alias protocol")
	cmd.Flags().BoolVar(&disabled, "disabled", false, "create in disabled state")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "validate and print action without persisting")
	return cmd
}

func newAliasListCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "list",
		Short: "List aliases and their target chains",
		Long: `alias list prints aliases from local ocswitch config together with their target
chains.

Output shows alias enabled state, target order, target enabled markers, and a
note when a referenced provider is missing or disabled. This is the easiest way
to verify failover order before running doctor or opencode sync.

This command does not modify config and does not contact upstream providers.`,
		Example: `  ocswitch alias list
  ocswitch --config /path/to/config.json alias list`,
		RunE: func(cmd *cobra.Command, args []string) error {
			svc := appService()
			aliases, err := svc.ListAliases(cmd.Context())
			if err != nil {
				return err
			}
			providers, err := svc.ListProviders(cmd.Context())
			if err != nil {
				return err
			}
			providerByID := make(map[string]app.ProviderView, len(providers))
			for _, p := range providers {
				providerByID[p.ID] = p
			}
			if len(aliases) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "(no aliases)")
				return nil
			}
			for _, a := range aliases {
				state := "enabled"
				if !a.Enabled {
					state = "disabled"
				}
				kind := "custom"
				order := "-"
				if a.AutoGenerated {
					kind = "auto-model"
					order = config.TargetOrderModeProviderPriority
					if a.TargetOrderMode == config.TargetOrderModeCustom {
						order = config.TargetOrderModeCustom
					}
				}
				fmt.Fprintf(cmd.OutOrStdout(), "%s  [%s] [%s] [%s] order=%s\n", a.Alias, state, kind, config.NormalizeAliasProtocol(a.Protocol), order)
				for i, t := range a.Targets {
					mark := "x"
					if !t.Enabled {
						mark = " "
					}
					note := ""
					p, ok := providerByID[t.Provider]
					switch {
					case !ok:
						note = " (missing provider)"
					case p.Disabled:
						note = " (provider disabled)"
					}
					groupID := t.Group
					if strings.TrimSpace(groupID) == "" {
						groupID = config.DefaultGroupID
					}
					fmt.Fprintf(cmd.OutOrStdout(), "  [%s] %d. %s/%s/%s%s\n", mark, i+1, t.Provider, groupID, t.Model, note)
				}
			}
			return nil
		},
	}
}

func newAliasBindCmd() *cobra.Command {
	var alias, provider, group, model string
	var disabled bool
	var dryRun bool
	cmd := &cobra.Command{
		Use:   "bind",
		Short: "Append a target (provider/group/model) to an alias in failover order",
		Long: `alias bind appends one provider/group/model target to an alias's ordered failover
chain in local ocswitch config via Service.

The provider must already exist. If the alias does not exist yet, this command
auto-creates an enabled alias for convenience. For the default group you can pass the target either as --provider <id>
--model <name> or in the combined form --model <provider>/<model> when
--provider is omitted; the combined form is recommended for simple model ids.
Models whose ids contain slashes require an explicit
--provider so the combined form is not ambiguous.

Non-default --group values require fully independent flags: --provider,
--group, and --model (model is never parsed as provider/model). This avoids
ambiguous provider/group/model vs provider/model splits.

If the selected group has a stored model catalog discovered from /v1/models,
bind validates the model name against that discovered list.

Order matters: the first bound target is tried first, the second is fallback,
and so on. Binding a custom target to an automatic model alias is a user override
and keeps future catalog sync. Typical next step: inspect with alias list, then
run doctor.`,
		Example: `  ocswitch alias bind --alias gpt-5.4 --model su8/gpt-5.4
  ocswitch alias bind --alias gpt-5.4 --model codex/GPT-5.4
  ocswitch alias bind --alias gpt-5.4 --provider relay --model gpt-5.4 --disabled
  ocswitch alias bind --alias gpt-5.4 --provider su8 --group premium --model gpt-5.4
  ocswitch alias bind --alias gemini --provider relay --group premium --model openrouter/google/gemini-2.5-pro`,

		RunE: func(cmd *cobra.Command, args []string) error {
			if alias == "" || model == "" {
				return fmt.Errorf("--alias and --model are required")
			}
			resolvedProvider, resolvedModel, resolvedGroup, err := resolveAliasTargetFlags(provider, group, model)
			if err != nil {
				return err
			}
			provider, model, group = resolvedProvider, resolvedModel, resolvedGroup
			if dryRun {
				fmt.Fprintf(cmd.OutOrStdout(), "dry-run: would bind %s → %s/%s/%s via Service/ConfigStore\n", alias, provider, group, model)
				return nil
			}
			view, err := appService().BindAliasTarget(cmd.Context(), app.AliasTargetInput{
				Alias:    alias,
				Provider: provider,
				Group:    group,
				Model:    model,
				Disabled: disabled,
			})
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "bound %s [%s] → %s/%s/%s\n", view.Alias, view.Protocol, provider, group, model)
			return nil
		},
	}
	cmd.Flags().StringVar(&alias, "alias", "", "alias name (required)")
	cmd.Flags().StringVar(&provider, "provider", "", "upstream provider id (required for non-default --group; else optional with --model provider/model)")
	cmd.Flags().StringVar(&group, "group", "", "provider group id (default: default; non-default requires --provider and literal --model)")
	cmd.Flags().StringVar(&model, "model", "", "upstream target model, or provider/model when --provider is omitted on default group (required)")
	cmd.Flags().BoolVar(&disabled, "disabled", false, "add target in disabled state")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "validate and print action without persisting")
	return cmd
}

func newAliasUnbindCmd() *cobra.Command {
	var alias, provider, group, model string
	var dryRun bool
	cmd := &cobra.Command{
		Use:   "unbind",
		Short: "Remove a target from an alias",
		Long: `alias unbind removes one concrete provider/group/model target tuple from an alias in
local ocswitch config via Service.

It does not delete the alias itself. Removing a target can leave the alias with
no routable targets, which doctor and opencode sync will then treat as invalid
or unavailable.

For the default group you can identify the target as --provider <id>
--model <name> or combined --model <provider>/<model> when --provider is
omitted. Non-default --group requires independent --provider, --group, and
literal --model (no provider/model parsing).`,
		Example: `  ocswitch alias unbind --alias gpt-5.4 --model codex/GPT-5.4
  ocswitch alias unbind --alias gpt-5.4 --provider codex --model GPT-5.4 --group premium
  ocswitch doctor`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if alias == "" || model == "" {
				return fmt.Errorf("--alias and --model are required")
			}
			resolvedProvider, resolvedModel, resolvedGroup, err := resolveAliasTargetFlags(provider, group, model)
			if err != nil {
				return err
			}
			provider, model, group = resolvedProvider, resolvedModel, resolvedGroup
			if dryRun {
				fmt.Fprintf(cmd.OutOrStdout(), "dry-run: would unbind %s → %s/%s/%s via Service/ConfigStore\n", alias, provider, group, model)
				return nil
			}
			if _, err := appService().UnbindAliasTarget(cmd.Context(), app.AliasTargetInput{
				Alias:    alias,
				Provider: provider,
				Group:    group,
				Model:    model,
			}); err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "unbound %s → %s/%s/%s\n", alias, provider, group, model)
			return nil
		},
	}
	cmd.Flags().StringVar(&alias, "alias", "", "alias name (required)")
	cmd.Flags().StringVar(&provider, "provider", "", "upstream provider id (required for non-default --group; else optional with --model provider/model)")
	cmd.Flags().StringVar(&group, "group", "", "provider group id (default: default; non-default requires --provider and literal --model)")
	cmd.Flags().StringVar(&model, "model", "", "upstream target model, or provider/model when --provider is omitted on default group (required)")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "validate and print action without persisting")
	return cmd
}

func newAliasResetOrderCmd() *cobra.Command {
	var dryRun bool
	cmd := &cobra.Command{
		Use:   "reset-order <alias>",
		Args:  cobra.ExactArgs(1),
		Short: "Reset alias target order to Provider Priority",
		Long: `alias reset-order changes an alias target list back to Provider Priority order.

This is most useful after manually reordering an automatic model alias. Future
Provider Priority changes will reorder the alias again until you drag or reorder
targets manually.`,
		Example: `  ocswitch alias reset-order gpt-5.4
  ocswitch alias list`,
		RunE: func(cmd *cobra.Command, args []string) error {
			name := strings.TrimSpace(args[0])
			if name == "" {
				return fmt.Errorf("alias name is required")
			}
			if dryRun {
				fmt.Fprintf(cmd.OutOrStdout(), "dry-run: would reset target order for %q via Service/ConfigStore\n", name)
				return nil
			}
			view, err := appService().ResetAliasTargetOrder(cmd.Context(), app.AliasLockInput{Name: name})
			if err != nil {
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "reset target order for %q (%d target(s))\n", view.Alias, len(view.Targets))
			return nil
		},
	}
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "validate and print action without persisting")
	return cmd
}

func newAliasRemoveCmd() *cobra.Command {
	var dryRun bool
	var yes bool
	cmd := &cobra.Command{
		Use:   "remove <alias>",
		Args:  cobra.ExactArgs(1),
		Short: "Delete an alias entirely",
		Long: `alias remove deletes one alias and all of its target bindings from local ocswitch
config via Service lifecycle planning.

Rewrite selector impacts default to keep_rule on this convenience path.
Use --dry-run to print the impact plan without persisting. Non-interactive
shells require --yes to execute. Use --json for a single envelope on stdout.`,
		Example: `  ocswitch alias remove gpt-5.4 --dry-run
  ocswitch alias remove gpt-5.4 --yes
  ocswitch opencode sync`,
		RunE: func(cmd *cobra.Command, args []string) error {
			name := strings.TrimSpace(args[0])
			rev, plan, selections, err := previewRemoveAliasWithSelections(cmd, name)
			if err != nil {
				return finishOutcome(cmd, err, nil)
			}
			payload, _ := marshalPayload(lifecycle.AliasRemovePayload{Alias: name})
			op := lifecycle.Operation{Kind: lifecycle.OpAliasRemove, Payload: payload}

			if jsonOutput && dryRun {
				_, env := app.ClassifyOutcome(nil, plan)
				return writeJSONEnvelope(cmd.OutOrStdout(), env)
			}
			if !jsonOutput {
				if dryRun {
					fmt.Fprintf(cmd.OutOrStdout(), "dry-run: would remove alias %q\n", name)
				}
				printPlanHuman(cmd.OutOrStdout(), plan)
			}
			if dryRun {
				return nil
			}
			if !plan.Executable || strings.TrimSpace(plan.PlanToken) == "" {
				return finishOutcome(cmd, &app.OutcomeError{
					Code: "plan_not_executable",
					Params: map[string]any{
						"operationKind": lifecycle.OpAliasRemove,
						"alias":         name,
						"blockerCount":  len(plan.Blockers),
						"choiceCount":   len(plan.Choices),
					},
				}, plan)
			}
			ok, cerr := confirmExecute(cmd, yes)
			if cerr != nil {
				return finishOutcome(cmd, cerr, plan)
			}
			if !ok {
				fmt.Fprintln(cmd.OutOrStdout(), "aborted")
				return nil
			}
			result, err := executeLifecyclePlan(cmd, rev, plan, op, selections)
			if err != nil {
				return finishOutcome(cmd, err, result)
			}
			if jsonOutput {
				_, env := app.ClassifyOutcome(nil, result)
				return writeJSONEnvelope(cmd.OutOrStdout(), env)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "removed alias %q\n", name)
			printExecuteHuman(cmd.OutOrStdout(), result)
			return nil
		},
	}
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "preview impact plan without persisting")
	cmd.Flags().BoolVar(&yes, "yes", false, "execute without interactive confirmation")
	return cmd
}

// resolveCLIGroupID maps an omitted/blank group flag only to the default group.
// It never expands to a sibling group under the provider.
func resolveCLIGroupID(group string) string {
	group = strings.TrimSpace(group)
	if group == "" {
		return config.DefaultGroupID
	}
	return group
}

// resolveAliasTargetFlags resolves CLI provider/group/model flags for bind/unbind.
// Default-group legacy UX keeps --model provider/model when --provider is omitted.
// Non-default groups require explicit independent --provider and a literal --model
// so slash-containing model ids are never ambiguous with provider/model refs.
func resolveAliasTargetFlags(provider, group, model string) (string, string, string, error) {
	provider = strings.TrimSpace(provider)
	rawGroup := strings.TrimSpace(group)
	model = strings.TrimSpace(model)
	if rawGroup != "" && rawGroup != config.DefaultGroupID {
		if provider == "" {
			return "", "", "", fmt.Errorf("--provider is required when --group is not %q (non-default groups require independent --provider/--group/--model)", config.DefaultGroupID)
		}
		if model == "" {
			return "", "", "", fmt.Errorf("--model is required")
		}
		return provider, model, rawGroup, nil
	}
	combinedProvider, combinedModel, combined := parseProviderModelRef(model)
	if provider == "" {
		if !combined {
			return "", "", "", fmt.Errorf("--model must use <provider>/<model> when --provider is omitted")
		}
		provider = combinedProvider
		model = combinedModel
	}
	return provider, model, resolveCLIGroupID(group), nil
}
