package diagnostics

import (
	"fmt"
	"strings"

	"github.com/Apale7/opencode-provider-switch/internal/config"
)

type ScanOptions struct {
	CatalogStates map[string]string
}

func ScanConfig(cfg *config.Config, options ScanOptions) ([]Issue, error) {
	if cfg == nil {
		return nil, fmt.Errorf("scan config: nil config")
	}
	var issues []Issue
	providerIndexes := map[string][]int{}
	for i, provider := range cfg.Providers {
		providerIndexes[provider.ID] = append(providerIndexes[provider.ID], i)
	}
	for i, provider := range cfg.Providers {
		if state := options.CatalogStates[provider.ID]; state != "" && validCatalogStates[state] {
			issues = append(issues, issue(CodeProviderCatalogStale, SeverityWarning, ReasonCatalogStale,
				fmt.Sprintf("/config/providers/%d/models", i), Source{"provider", occurrenceKey(provider.ID, i, providerIndexes), fmt.Sprintf("/config/providers/%d", i)}, &Target{"model_catalog", occurrenceKey(provider.ID, i, providerIndexes), nil}, nil,
				Params{"providerId": provider.ID, "catalogState": state}))
		}
	}
	providers := map[string]config.Provider{}
	for id, indexes := range providerIndexes {
		if len(indexes) > 1 {
			issues = append(issues, ambiguous(CodeProviderIdentityAmbiguous, "provider", indexes, "/config/providers", Params{"providerId": id})...)
		} else {
			providers[id] = cfg.Providers[indexes[0]]
		}
	}

	aliasIndexes := map[string][]int{}
	for ai, alias := range cfg.Aliases {
		aliasIndexes[alias.Alias] = append(aliasIndexes[alias.Alias], ai)
	}
	for ai, alias := range cfg.Aliases {
		aliasPath := fmt.Sprintf("/config/aliases/%d", ai)
		aliasKey := occurrenceKey(alias.Alias, ai, aliasIndexes)
		aliasAmbiguous := len(aliasIndexes[alias.Alias]) > 1
		if !alias.Enabled {
			actions := []Action{ActionEnableAlias, ActionKeep}
			if aliasAmbiguous {
				actions = nil
			}
			issues = append(issues, issue(CodeAliasDisabled, SeverityInfo, ReasonDisabled, aliasPath+"/enabled", Source{"alias", aliasKey, aliasPath}, nil, actions, Params{"alias": alias.Alias}))
		}
		targetIDs := map[string][]int{}
		for ti, target := range alias.Targets {
			identity := target.Provider + "\x00" + target.Model
			targetIDs[identity] = append(targetIDs[identity], ti)
		}
		missing, disabled, mismatch, uncertain := 0, 0, 0, 0
		for ti, target := range alias.Targets {
			targetPath := fmt.Sprintf("%s/targets/%d", aliasPath, ti)
			identity := target.Provider + "\x00" + target.Model
			targetKey := occurrenceKey(identity, ti, targetIDs)
			params := Params{"alias": alias.Alias, "targetIndex": ti, "providerId": target.Provider, "model": target.Model}
			provider, exists := providers[target.Provider]
			ambiguousProvider := len(providerIndexes[target.Provider]) > 1
			actions := targetActions(alias)
			if aliasAmbiguous || len(targetIDs[identity]) > 1 {
				actions = nil
			}
			switch {
			case ambiguousProvider:
				// The provider ambiguity issue is authoritative; do not infer
				// availability or executable target actions from one occurrence.
				uncertain++
			case !exists:
				missing++
				issues = append(issues, issue(CodeAliasTargetProviderMissing, SeverityError, ReasonMissing, targetPath+"/provider", Source{"alias_target", targetKey, targetPath}, &Target{"provider", target.Provider, nil}, actions, params))
			case !config.ProtocolsMatch(alias.Protocol, provider.Protocol):
				mismatch++
				params["aliasProtocol"] = config.NormalizeAliasProtocol(alias.Protocol)
				params["providerProtocol"] = config.NormalizeProviderProtocol(provider.Protocol)
				issues = append(issues, issue(CodeAliasTargetProtocolMismatch, SeverityError, ReasonProtocolMismatch, targetPath+"/provider", Source{"alias_target", targetKey, targetPath}, &Target{"provider", target.Provider, nil}, actions, params))
			case !target.Enabled:
				disabled++
				if !alias.AutoGenerated && !alias.Locked && !aliasAmbiguous && len(targetIDs[identity]) == 1 {
					actions = append(actions, ActionEnableTarget)
				}
				issues = append(issues, issue(CodeAliasTargetDisabled, SeverityInfo, ReasonDisabled, targetPath+"/enabled", Source{"alias_target", targetKey, targetPath}, nil, actions, params))
			case provider.Disabled:
				disabled++
				if actions != nil {
					actions = append(actions, ActionEnableProvider, ActionKeep)
				}
				issues = append(issues, issue(CodeAliasTargetProviderDisabled, SeverityWarning, ReasonDisabled, targetPath+"/provider", Source{"alias_target", targetKey, targetPath}, &Target{"provider", target.Provider, nil}, actions, params))
			case validCatalogStates[options.CatalogStates[target.Provider]]:
				params["catalogState"] = options.CatalogStates[target.Provider]
				if actions != nil {
					actions = append(actions, ActionRefreshCatalog, ActionKeep)
				}
				issues = append(issues, issue(CodeAliasTargetModelUnconfirmed, SeverityInfo, ReasonCatalogStale, targetPath+"/model", Source{"alias_target", targetKey, targetPath}, &Target{"model_symbol", target.Model, nil}, actions, params))
			}
		}
		for identity, indexes := range targetIDs {
			if len(indexes) > 1 {
				parts := strings.SplitN(identity, "\x00", 2)
				issues = append(issues, ambiguous(CodeAliasTargetIdentityAmbiguous, "alias_target", indexes, aliasPath+"/targets", Params{
					"alias": alias.Alias, "providerId": parts[0], "model": parts[1],
				})...)
			}
		}
		if alias.Enabled && (len(alias.Targets) == 0 || missing+disabled+mismatch+uncertain == len(alias.Targets)) {
			issues = append(issues, issue(CodeAliasNoAvailableTarget, SeverityWarning, ReasonNoAvailableTarget, aliasPath, Source{"alias", aliasKey, aliasPath}, nil, nil, Params{"alias": alias.Alias, "targetCount": len(alias.Targets), "missingCount": missing, "disabledCount": disabled, "protocolMismatchCount": mismatch, "ambiguousCount": uncertain}))
		}
	}
	aliases := map[string]bool{}
	for id, indexes := range aliasIndexes {
		if len(indexes) > 1 {
			issues = append(issues, ambiguous(CodeAliasIdentityAmbiguous, "alias", indexes, "/config/aliases", Params{"alias": id})...)
		} else {
			aliases[id] = true
		}
	}

	rewriteIndexes := map[string][]int{}
	for ri, rule := range cfg.RequestRewriteRules {
		rewriteIndexes[rule.Name] = append(rewriteIndexes[rule.Name], ri)
	}
	for ri, rule := range cfg.RequestRewriteRules {
		rulePath := fmt.Sprintf("/config/request_rewrite_rules/%d", ri)
		ruleKey := occurrenceKey(rule.Name, ri, rewriteIndexes)
		ruleAmbiguous := len(rewriteIndexes[rule.Name]) > 1
		if !aliases[rule.Alias] && len(aliasIndexes[rule.Alias]) <= 1 {
			actions := []Action{ActionReplaceSelector, ActionDisableRule, ActionDeleteRule, ActionKeep}
			if ruleAmbiguous {
				actions = nil
			}
			issues = append(issues, issue(CodeRewriteAliasUnresolved, SeverityInfo, ReasonMissing, rulePath+"/alias", Source{"rewrite_rule", ruleKey, rulePath}, &Target{"alias", rule.Alias, nil}, actions, Params{"ruleName": rule.Name, "ruleIndex": ri, "alias": rule.Alias, "directFallbackPossible": true}))
		}
		for si, providerID := range rule.Providers {
			if _, exists := providers[providerID]; exists {
				continue
			}
			if len(providerIndexes[providerID]) > 1 {
				continue
			}
			actions := []Action{ActionReplaceSelector, ActionDisableRule, ActionDeleteRule, ActionKeep}
			if len(rule.Providers) > 1 {
				actions = append(actions, ActionRemoveSelector)
			}
			if ruleAmbiguous {
				actions = nil
			}
			issues = append(issues, issue(CodeRewriteProviderMissing, SeverityWarning, ReasonMissing, fmt.Sprintf("%s/providers/%d", rulePath, si), Source{"rewrite_rule", ruleKey, rulePath}, &Target{"provider", providerID, nil}, actions, Params{"ruleName": rule.Name, "ruleIndex": ri, "providerId": providerID, "selectorIndex": si, "selectorCount": len(rule.Providers), "wildcardIfEmpty": true}))
		}
	}
	for id, indexes := range rewriteIndexes {
		if len(indexes) > 1 {
			issues = append(issues, ambiguous(CodeRewriteIdentityAmbiguous, "rewrite_rule", indexes, "/config/request_rewrite_rules", Params{"ruleName": id})...)
		}
	}
	for pi, providerID := range cfg.ProviderPriority {
		if len(providerIndexes[providerID]) > 1 {
			continue
		}
		if _, exists := providers[providerID]; !exists {
			issues = append(issues, issue(CodePriorityProviderMissing, SeverityInfo, ReasonMissing, fmt.Sprintf("/config/provider_priority/%d", pi), Source{"priority_entry", fmt.Sprintf("@index:%d", pi), fmt.Sprintf("/config/provider_priority/%d", pi)}, &Target{"provider", providerID, nil}, []Action{ActionRemovePriorityEntry, ActionKeep}, Params{"providerId": providerID, "priorityIndex": pi}))
		}
	}
	return SortAndDedupe(issues)
}

func issue(code Code, severity Severity, reason Reason, path string, source Source, target *Target, actions []Action, params Params) Issue {
	return Issue{SchemaVersion: SchemaVersion, Code: code, Severity: severity, Path: path, Source: source, Target: target, Reason: reason, AllowedActions: actions, Params: params}
}

func ambiguous(code Code, kind EntityKind, indexes []int, root string, params Params) []Issue {
	paths := make([]string, len(indexes))
	for i, index := range indexes {
		paths[i] = fmt.Sprintf("%s/%d", root, index)
	}
	issues := make([]Issue, 0, len(indexes))
	for _, index := range indexes {
		occurrenceParams := make(Params, len(params)+2)
		for key, value := range params {
			occurrenceParams[key] = value
		}
		occurrenceParams["occurrenceCount"] = len(indexes)
		occurrenceParams["occurrencePaths"] = paths
		path := fmt.Sprintf("%s/%d", root, index)
		issues = append(issues, issue(code, SeverityError, ReasonAmbiguous, path, Source{kind, fmt.Sprintf("@index:%d", index), path}, nil, nil, occurrenceParams))
	}
	return issues
}

func targetActions(alias config.Alias) []Action {
	if alias.AutoGenerated || alias.Locked {
		return []Action{ActionUpgradeAlias, ActionDeleteAlias}
	}
	return []Action{ActionRebindTarget, ActionRemoveTarget, ActionDeleteAlias}
}

func occurrenceKey(value string, index int, indexes map[string][]int) string {
	if value == "" || len(indexes[value]) > 1 {
		return fmt.Sprintf("@index:%d", index)
	}
	return value
}
