// Package config manages the local ocswitch JSON config file.
package config

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"sync"

	"github.com/Apale7/opencode-provider-switch/internal/fileutil"
	"github.com/Apale7/opencode-provider-switch/internal/routing"
)

const (
	AppName            = "ocswitch"
	ConfigEnvVar       = "OCSWITCH_CONFIG"
	ConfigDirName      = "ocswitch"
	DefaultLocalAPIKey = "ocswitch-local"
)

// Target is one concrete upstream candidate for an alias.
type Target struct {
	Provider      string `json:"provider"`
	Group         string `json:"group,omitempty"`
	Model         string `json:"model"`
	Enabled       bool   `json:"enabled"`
	AutoGenerated bool   `json:"auto_generated,omitempty"` // 是否由系统自动添加
}

// TargetRef identifies one alias target without mutable state.
type TargetRef struct {
	Provider string
	Group    string
	Model    string
}

// RequestRewriteRule rewrites outbound request config for a matching alias and
// selected provider groups. Empty ProviderGroups means all groups for that alias.
// Set and Delete are legacy fields kept only to detect inactive old rules.
type RequestRewriteRule struct {
	Name           string                    `json:"name"`
	Alias          string                    `json:"alias,omitempty"`
	ProviderGroups []ProviderGroupSelector   `json:"provider_groups,omitempty"`
	Enabled        bool                      `json:"enabled"`
	Override       bool                      `json:"override,omitempty"`
	Ops            []RequestRewriteOperation `json:"ops,omitempty"`
	Set            map[string]any            `json:"set,omitempty"`
	Delete         []string                  `json:"delete,omitempty"`
}

// Alias maps a logical model name to ordered upstream targets.
type Alias struct {
	Alias         string   `json:"alias"`
	DisplayName   string   `json:"display_name,omitempty"`
	Protocol      string   `json:"protocol,omitempty"`
	Enabled       bool     `json:"enabled"`
	Targets       []Target `json:"targets"`
	AutoGenerated bool     `json:"auto_generated,omitempty"` // 是否由系统自动生成
	Locked        bool     `json:"locked,omitempty"`         // 是否锁定（禁止自动修改）
}

// Provider is one upstream service with shared connection settings and groups.
type Provider struct {
	ID              string            `json:"id"`
	Name            string            `json:"name,omitempty"`
	BaseURL         string            `json:"base_url"`
	BaseURLs        []string          `json:"base_urls,omitempty"`
	BaseURLStrategy string            `json:"base_url_strategy,omitempty"`
	Headers         map[string]string `json:"headers,omitempty"`
	Disabled        bool              `json:"disabled,omitempty"`
	// AutoAliasEnabled controls per-provider auto-alias generation.
	// Nil means enabled (legacy configs default to true).
	AutoAliasEnabled *bool           `json:"auto_alias_enabled,omitempty"`
	Groups           []ProviderGroup `json:"groups,omitempty"`
}

const (
	ProviderBaseURLStrategyOrdered = "ordered"
	ProviderBaseURLStrategyLatency = "latency"
)

// Server holds proxy listen settings.
type Server struct {
	Host                             string         `json:"host"`
	Port                             int            `json:"port"`
	APIKey                           string         `json:"api_key"`
	ConnectTimeoutMs                 int            `json:"connect_timeout_ms,omitempty"`
	ResponseHeaderTimeoutMs          int            `json:"response_header_timeout_ms,omitempty"`
	FirstByteTimeoutMs               int            `json:"first_byte_timeout_ms,omitempty"`
	RequestReadTimeoutMs             int            `json:"request_read_timeout_ms,omitempty"`
	StreamIdleTimeoutMs              int            `json:"stream_idle_timeout_ms,omitempty"`
	StreamPrecommitBufferMs          int            `json:"stream_precommit_buffer_ms,omitempty"`
	ExcludeFirstTokenLatencyFromRate bool           `json:"exclude_first_token_latency_from_rate"`
	FailoverStatusCodes              []int          `json:"failover_status_codes"`
	Routing                          routing.Config `json:"routing,omitempty"`
}

// Admin holds the server-mode web administration listener and token.
type Admin struct {
	Host          string `json:"host,omitempty"`
	Port          int    `json:"port,omitempty"`
	APIKey        string `json:"api_key,omitempty"`
	PublicBaseURL string `json:"public_base_url,omitempty"`
}

const (
	DefaultConnectTimeoutMs                 = 10_000
	DefaultResponseHeaderTimeoutMs          = 15_000
	DefaultFirstByteTimeoutMs               = 15_000
	DefaultRequestReadTimeoutMs             = 30_000
	DefaultStreamIdleTimeoutMs              = 60_000
	DefaultStreamPrecommitBufferMs          = 0
	DefaultExcludeFirstTokenLatencyFromRate = true
)

var defaultFailoverStatusCodes = []int{401, 402, 403, 429}

func DefaultFailoverStatusCodes() []int {
	return cloneInts(defaultFailoverStatusCodes)
}

// Desktop holds desktop-shell user preferences.
type Desktop struct {
	LaunchAtLogin  bool   `json:"launch_at_login,omitempty"`
	AutoStartProxy bool   `json:"auto_start_proxy,omitempty"`
	MinimizeToTray bool   `json:"minimize_to_tray,omitempty"`
	Notifications  bool   `json:"notifications,omitempty"`
	Theme          string `json:"theme,omitempty"`
	Language       string `json:"language,omitempty"`
}

// Config is the on-disk ocswitch config.
type Config struct {
	SchemaVersion int        `json:"schema_version,omitempty"`
	Server        Server     `json:"server"`
	Admin         Admin      `json:"admin,omitempty"`
	Desktop       Desktop    `json:"desktop,omitempty"`
	Providers     []Provider `json:"providers"`
	Aliases       []Alias    `json:"aliases"`

	RequestRewriteRules []RequestRewriteRule `json:"request_rewrite_rules,omitempty"`
	ProviderPriority    []string             `json:"provider_priority,omitempty"`  // 按优先级排序的 provider ID 列表
	AutoAliasEnabled    bool                 `json:"auto_alias_enabled,omitempty"` // 全局自动 alias 开关（默认 true）

	path             string
	loadedFromLegacy bool // set when disk bytes were schema v1 / missing version
	mu               sync.RWMutex
}

// IsEnabled reports whether the provider can be used for routing.
func (p Provider) IsEnabled() bool {
	return !p.Disabled
}

// EffectiveAutoAliasEnabled reports whether this provider participates in
// automatic alias generation. Nil (legacy) defaults to true.
func (p Provider) EffectiveAutoAliasEnabled() bool {
	if p.AutoAliasEnabled == nil {
		return true
	}
	return *p.AutoAliasEnabled
}

// IsAutoAliasEnabled is equivalent to EffectiveAutoAliasEnabled.
func (p Provider) IsAutoAliasEnabled() bool {
	return p.EffectiveAutoAliasEnabled()
}

// EffectiveBaseURLs returns the provider's normalized upstream base URL list.
func (p Provider) EffectiveBaseURLs() []string {
	return NormalizeProviderBaseURLs(p.BaseURL, p.BaseURLs)
}

// NormalizeProviderBaseURL canonicalizes equivalent /v1 roots for comparisons
// and persisted config values.
func NormalizeProviderBaseURL(baseURL string) string {
	return strings.TrimRight(strings.TrimSpace(baseURL), "/")
}

// NormalizeProviderBaseURLs canonicalizes, deduplicates, and preserves order.
func NormalizeProviderBaseURLs(primary string, baseURLs []string) []string {
	combined := make([]string, 0, len(baseURLs)+1)
	if primary != "" {
		combined = append(combined, primary)
	}
	combined = append(combined, baseURLs...)
	seen := map[string]bool{}
	out := make([]string, 0, len(combined))
	for _, item := range combined {
		normalized := NormalizeProviderBaseURL(item)
		if normalized == "" || seen[normalized] {
			continue
		}
		seen[normalized] = true
		out = append(out, normalized)
	}
	return out
}

// NormalizeProviderAPIKeys canonicalizes, deduplicates, and preserves order.
func NormalizeProviderAPIKeys(primary string, apiKeys []string) []string {
	combined := make([]string, 0, len(apiKeys)+1)
	if primary != "" {
		combined = append(combined, primary)
	}
	combined = append(combined, apiKeys...)
	seen := map[string]bool{}
	out := make([]string, 0, len(combined))
	for _, item := range combined {
		trimmed := strings.TrimSpace(item)
		if trimmed == "" || seen[trimmed] {
			continue
		}
		seen[trimmed] = true
		out = append(out, trimmed)
	}
	return out
}

func NormalizeProviderBaseURLStrategy(strategy string) string {
	switch strings.TrimSpace(strategy) {
	case "", ProviderBaseURLStrategyOrdered:
		return ProviderBaseURLStrategyOrdered
	case ProviderBaseURLStrategyLatency:
		return ProviderBaseURLStrategyLatency
	default:
		return ProviderBaseURLStrategyOrdered
	}
}

func ValidateProviderBaseURLStrategy(strategy string) error {
	strategy = NormalizeProviderBaseURLStrategy(strategy)
	if strategy == ProviderBaseURLStrategyOrdered || strategy == ProviderBaseURLStrategyLatency {
		return nil
	}
	return fmt.Errorf("unknown base_url_strategy %q", strategy)
}

func ValidateProviderBaseURLs(protocol string, primary string, baseURLs []string) error {
	urls := NormalizeProviderBaseURLs(primary, baseURLs)
	if len(urls) == 0 {
		return fmt.Errorf("missing base_url")
	}
	for _, item := range urls {
		if err := ValidateProviderBaseURL(protocol, item); err != nil {
			return err
		}
	}
	return nil
}

// ValidateProviderBaseURL checks protocol-specific upstream base URL rules.
func ValidateProviderBaseURL(protocol string, baseURL string) error {
	protocol = NormalizeProviderProtocol(protocol)
	if err := ValidateProtocol(protocol); err != nil {
		return err
	}
	trimmed := NormalizeProviderBaseURL(baseURL)
	if trimmed == "" {
		return fmt.Errorf("missing base_url")
	}
	return nil
}

// Default returns an empty config with sane defaults.
func Default() *Config {
	return &Config{
		SchemaVersion: CurrentSchemaVersion,
		Server: Server{
			Host:                             "127.0.0.1",
			Port:                             9982,
			APIKey:                           DefaultLocalAPIKey,
			ConnectTimeoutMs:                 DefaultConnectTimeoutMs,
			ResponseHeaderTimeoutMs:          DefaultResponseHeaderTimeoutMs,
			FirstByteTimeoutMs:               DefaultFirstByteTimeoutMs,
			RequestReadTimeoutMs:             DefaultRequestReadTimeoutMs,
			StreamIdleTimeoutMs:              DefaultStreamIdleTimeoutMs,
			StreamPrecommitBufferMs:          DefaultStreamPrecommitBufferMs,
			ExcludeFirstTokenLatencyFromRate: DefaultExcludeFirstTokenLatencyFromRate,
			FailoverStatusCodes:              DefaultFailoverStatusCodes(),
			Routing:                          routing.Config{Strategy: routing.DefaultStrategy},
		},
		Admin: Admin{
			Host: "127.0.0.1",
			Port: 9983,
		},
		Desktop:             Desktop{},
		Providers:           []Provider{},
		Aliases:             []Alias{},
		RequestRewriteRules: []RequestRewriteRule{},
		ProviderPriority:    []string{},
		AutoAliasEnabled:    true,
	}
}

// DefaultPath returns ~/.config/ocswitch/config.json (XDG aware).
func DefaultPath() string {
	if p := os.Getenv(ConfigEnvVar); p != "" {
		return p
	}
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, ConfigDirName, "config.json")
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return AppName + "-config.json"
	}
	return filepath.Join(home, ".config", ConfigDirName, "config.json")
}

// Load reads the config at path. Missing file returns a default config anchored to path.
// Load never writes disk and never changes ConfigStore revision.
func Load(path string) (*Config, error) {
	if path == "" {
		path = DefaultPath()
	}
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			c := Default()
			c.path = path
			return c, nil
		}
		return nil, fmt.Errorf("read config: %w", err)
	}
	return finalizeLoadedConfig(path, data)
}

func configHasExplicitServerAPIKey(data []byte) bool {
	var raw struct {
		Server *struct {
			APIKey *string `json:"api_key"`
		} `json:"server"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return false
	}
	return raw.Server != nil && raw.Server.APIKey != nil
}

// Path returns the on-disk path of this config.
func (c *Config) Path() string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.path
}

// MarshalPersistent encodes config using the same normalization and field set as Save.
func (c *Config) MarshalPersistent() ([]byte, error) {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.marshalPersistentLocked()
}

func (c *Config) marshalPersistentLocked() ([]byte, error) {
	providers := cloneProviders(c.Providers)
	normalizeProviders(providers)
	sort.Slice(providers, func(i, j int) bool { return providers[i].ID < providers[j].ID })
	aliases := cloneAliases(c.Aliases)
	normalizeAliases(aliases)
	sort.Slice(aliases, func(i, j int) bool { return aliases[i].Alias < aliases[j].Alias })
	rewriteRules := cloneRequestRewriteRules(c.RequestRewriteRules)
	normalizeRequestRewriteRules(rewriteRules)
	server := c.Server
	normalizeServerTimeouts(&server)
	normalizeServerFailoverStatusCodes(&server)
	normalizeServerRouting(&server)

	// Canonical v2 wire shape — never emit deprecated provider projections or legacy rewrite providers.
	type persistGroup struct {
		ID           string   `json:"id"`
		Name         string   `json:"name,omitempty"`
		Protocol     string   `json:"protocol"`
		APIKey       string   `json:"api_key,omitempty"`
		APIKeys      []string `json:"api_keys,omitempty"`
		Models       []string `json:"models,omitempty"`
		ModelsSource string   `json:"models_source,omitempty"`
		Disabled     bool     `json:"disabled,omitempty"`
	}
	type persistProvider struct {
		ID               string            `json:"id"`
		Name             string            `json:"name,omitempty"`
		BaseURL          string            `json:"base_url"`
		BaseURLs         []string          `json:"base_urls,omitempty"`
		BaseURLStrategy  string            `json:"base_url_strategy,omitempty"`
		Headers          map[string]string `json:"headers,omitempty"`
		Disabled         bool              `json:"disabled,omitempty"`
		AutoAliasEnabled *bool             `json:"auto_alias_enabled,omitempty"`
		Groups           []persistGroup    `json:"groups"`
	}
	type persistTarget struct {
		Provider      string `json:"provider"`
		Group         string `json:"group"`
		Model         string `json:"model"`
		Enabled       bool   `json:"enabled"`
		AutoGenerated bool   `json:"auto_generated,omitempty"`
	}
	type persistAlias struct {
		Alias         string          `json:"alias"`
		DisplayName   string          `json:"display_name,omitempty"`
		Protocol      string          `json:"protocol,omitempty"`
		Enabled       bool            `json:"enabled"`
		Targets       []persistTarget `json:"targets"`
		AutoGenerated bool            `json:"auto_generated,omitempty"`
		Locked        bool            `json:"locked,omitempty"`
	}
	type persistRewrite struct {
		Name           string                    `json:"name"`
		Alias          string                    `json:"alias,omitempty"`
		ProviderGroups []ProviderGroupSelector   `json:"provider_groups,omitempty"`
		Enabled        bool                      `json:"enabled"`
		Override       bool                      `json:"override,omitempty"`
		Ops            []RequestRewriteOperation `json:"ops,omitempty"`
		Set            map[string]any            `json:"set,omitempty"`
		Delete         []string                  `json:"delete,omitempty"`
	}

	outProviders := make([]persistProvider, 0, len(providers))
	for _, p := range providers {
		groups := make([]persistGroup, 0, len(p.Groups))
		for _, g := range p.Groups {
			groups = append(groups, persistGroup{
				ID:           g.ID,
				Name:         g.Name,
				Protocol:     g.Protocol,
				APIKey:       g.APIKey,
				APIKeys:      g.APIKeys,
				Models:       g.Models,
				ModelsSource: g.ModelsSource,
				Disabled:     g.Disabled,
			})
		}
		outProviders = append(outProviders, persistProvider{
			ID:               p.ID,
			Name:             p.Name,
			BaseURL:          p.BaseURL,
			BaseURLs:         p.BaseURLs,
			BaseURLStrategy:  p.BaseURLStrategy,
			Headers:          p.Headers,
			Disabled:         p.Disabled,
			AutoAliasEnabled: p.AutoAliasEnabled,
			Groups:           groups,
		})
	}
	outAliases := make([]persistAlias, 0, len(aliases))
	for _, a := range aliases {
		targets := make([]persistTarget, 0, len(a.Targets))
		for _, t := range a.Targets {
			// Do not rewrite empty group to default; only the v1 decoder injects default.
			// Validate/ValidateForPersist fail closed on empty target groups.
			targets = append(targets, persistTarget{
				Provider:      t.Provider,
				Group:         strings.TrimSpace(t.Group),
				Model:         t.Model,
				Enabled:       t.Enabled,
				AutoGenerated: t.AutoGenerated,
			})
		}
		outAliases = append(outAliases, persistAlias{
			Alias:         a.Alias,
			DisplayName:   a.DisplayName,
			Protocol:      a.Protocol,
			Enabled:       a.Enabled,
			Targets:       targets,
			AutoGenerated: a.AutoGenerated,
			Locked:        a.Locked,
		})
	}
	outRules := make([]persistRewrite, 0, len(rewriteRules))
	for _, rule := range rewriteRules {
		// Always emit provider_groups key when the slice is non-nil (including explicit empty wildcard).
		item := persistRewrite{
			Name:     rule.Name,
			Alias:    rule.Alias,
			Enabled:  rule.Enabled,
			Override: rule.Override,
			Ops:      rule.Ops,
			Set:      rule.Set,
			Delete:   rule.Delete,
		}
		if rule.ProviderGroups != nil {
			item.ProviderGroups = rule.ProviderGroups
		}
		outRules = append(outRules, item)
	}

	snap := struct {
		SchemaVersion       int               `json:"schema_version"`
		Server              Server            `json:"server"`
		Admin               Admin             `json:"admin,omitempty"`
		Desktop             Desktop           `json:"desktop,omitempty"`
		Providers           []persistProvider `json:"providers"`
		Aliases             []persistAlias    `json:"aliases"`
		RequestRewriteRules []persistRewrite  `json:"request_rewrite_rules,omitempty"`
		ProviderPriority    []string          `json:"provider_priority,omitempty"`
		// Persist explicitly so false is not dropped by omitempty on reload.
		AutoAliasEnabled bool `json:"auto_alias_enabled"`
	}{
		SchemaVersion:       CurrentSchemaVersion,
		Server:              server,
		Admin:               c.Admin,
		Desktop:             c.Desktop,
		Providers:           outProviders,
		Aliases:             outAliases,
		RequestRewriteRules: outRules,
		ProviderPriority:    cloneStrings(c.ProviderPriority),
		AutoAliasEnabled:    c.AutoAliasEnabled,
	}
	data, err := json.MarshalIndent(snap, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal: %w", err)
	}
	// Ensure empty provider_groups arrays are preserved (omitempty would drop them).
	data, err = ensureEmptyProviderGroupsJSON(data, rewriteRules)
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

// ensureEmptyProviderGroupsJSON rewrites rules that intentionally use empty
// provider_groups wildcard so omitempty does not drop the key.
func ensureEmptyProviderGroupsJSON(data []byte, rules []RequestRewriteRule) ([]byte, error) {
	needs := false
	for _, rule := range rules {
		if rule.ProviderGroups != nil && len(rule.ProviderGroups) == 0 {
			needs = true
			break
		}
	}
	if !needs {
		return data, nil
	}
	var root map[string]any
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	if err := decoder.Decode(&root); err != nil {
		return nil, fmt.Errorf("marshal: %w", err)
	}
	rawRules, _ := root["request_rewrite_rules"].([]any)
	if len(rawRules) != len(rules) {
		return data, nil
	}
	for i, rule := range rules {
		if rule.ProviderGroups == nil || len(rule.ProviderGroups) != 0 {
			continue
		}
		item, ok := rawRules[i].(map[string]any)
		if !ok {
			continue
		}
		item["provider_groups"] = []any{}
		rawRules[i] = item
	}
	root["request_rewrite_rules"] = rawRules
	out, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal: %w", err)
	}
	return out, nil
}

// LoadFromBytes decodes config JSON for path without reading disk.
// Missing/empty data returns a default config anchored to path, matching Load.
// LoadFromBytes never writes disk and never changes ConfigStore revision.
func LoadFromBytes(path string, data []byte) (*Config, error) {
	if path == "" {
		path = DefaultPath()
	}
	return finalizeLoadedConfig(path, data)
}

func finalizeLoadedConfig(path string, data []byte) (*Config, error) {
	if len(data) == 0 {
		c := Default()
		c.path = path
		return c, nil
	}
	serverAPIKeyExplicit := configHasExplicitServerAPIKey(data)
	c, err := decodeConfigJSON(data)
	if err != nil {
		return nil, err
	}
	normalizeProviders(c.Providers)
	normalizeAliases(c.Aliases)
	normalizeRequestRewriteRules(c.RequestRewriteRules)
	c.ProviderPriority = c.normalizeProviderPriorityLocked(c.ProviderPriority)
	c.reorderUnlockedAutoAliasTargetsLocked()
	if c.Server.Host == "" {
		c.Server.Host = "127.0.0.1"
	}
	if c.Server.Port == 0 {
		c.Server.Port = 9982
	}
	if c.Server.APIKey == "" && !serverAPIKeyExplicit {
		c.Server.APIKey = DefaultLocalAPIKey
	}
	normalizeAdmin(&c.Admin)
	normalizeServerTimeouts(&c.Server)
	normalizeServerFailoverStatusCodes(&c.Server)
	normalizeServerRouting(&c.Server)
	c.SchemaVersion = CurrentSchemaVersion
	c.path = path
	return c, nil
}

// CloneDeep returns a detached deep copy of exported config fields.
func (c *Config) CloneDeep() (*Config, error) {
	raw, err := c.MarshalPersistent()
	if err != nil {
		return nil, err
	}
	return LoadFromBytes(c.Path(), raw)
}

// Save writes config atomically as schema v2.
// When the existing file is legacy schema, a sibling .bak is written first.
// Backup failure must not overwrite the original file.
func (c *Config) Save() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.path == "" {
		c.path = DefaultPath()
	}
	path := c.path
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	return fileutil.WithLockedFile(path, func() error {
		data, err := c.marshalPersistentLocked()
		if err != nil {
			return err
		}
		if err := BackupLegacyConfigFile(path); err != nil {
			return err
		}
		if err := fileutil.AtomicWriteFile(path, data, 0o600); err != nil {
			return err
		}
		c.loadedFromLegacy = false
		c.SchemaVersion = CurrentSchemaVersion
		return nil
	})
}

// BackupLegacyConfigFile writes path.bak from the current file when it is not schema v2.
// It is shared by Config.Save and transactional ConfigStore persistence hooks.
// An existing regular .bak file is preserved (first backup wins). A directory or
// unwritable backup target remains an error so callers can abort the upgrade write.
func BackupLegacyConfigFile(path string) error {
	existing, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("read config for backup: %w", err)
	}
	if !NeedsLegacyConfigBackup(existing) {
		return nil
	}
	backupPath := BackupPathForConfig(path)
	info, statErr := os.Stat(backupPath)
	if statErr == nil {
		if info.IsDir() {
			return fmt.Errorf("backup legacy config: %s is a directory", backupPath)
		}
		// First backup already present; never overwrite it.
		return nil
	}
	if !errors.Is(statErr, os.ErrNotExist) {
		return fmt.Errorf("stat legacy backup: %w", statErr)
	}
	if err := fileutil.AtomicWriteFile(backupPath, existing, 0o600); err != nil {
		return fmt.Errorf("backup legacy config: %w", err)
	}
	return nil
}

// FindProvider returns the provider with matching id or nil.
func (c *Config) FindProvider(id string) *Provider {
	c.mu.RLock()
	defer c.mu.RUnlock()
	p := c.findProviderLocked(id)
	if p == nil {
		return nil
	}
	clone := cloneProvider(*p)
	return &clone
}

func (c *Config) findProviderLocked(id string) *Provider {
	for i := range c.Providers {
		if c.Providers[i].ID == id {
			return &c.Providers[i]
		}
	}
	return nil
}

// UpsertProvider adds or replaces a provider by id.
// Empty Groups are stored as-is; only the v1 decoder injects a default group.
// Validate / ValidateForPersist fail closed when a provider has no groups.
func (c *Config) UpsertProvider(p Provider) {
	c.mu.Lock()
	defer c.mu.Unlock()
	cloned := cloneProvider(p)
	for i := range c.Providers {
		if c.Providers[i].ID == p.ID {
			c.Providers[i] = cloned
			return
		}
	}
	c.Providers = append(c.Providers, cloned)
}

// RemoveProvider deletes a provider and returns true if removed.
func (c *Config) RemoveProvider(id string) bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	for i := range c.Providers {
		if c.Providers[i].ID == id {
			c.Providers = append(c.Providers[:i], c.Providers[i+1:]...)
			return true
		}
	}
	return false
}

// FindAlias returns the manual (non-auto-generated) alias with matching name or nil.
func (c *Config) FindAlias(name string) *Alias {
	c.mu.RLock()
	defer c.mu.RUnlock()
	for i := range c.Aliases {
		if c.Aliases[i].Alias == name && !c.Aliases[i].AutoGenerated {
			clone := cloneAlias(c.Aliases[i])
			return &clone
		}
	}
	return nil
}

// FindAutoAlias returns the auto-generated alias with matching name or nil.
func (c *Config) FindAutoAlias(name string) *Alias {
	c.mu.RLock()
	defer c.mu.RUnlock()
	for i := range c.Aliases {
		if c.Aliases[i].Alias == name && c.Aliases[i].AutoGenerated {
			clone := cloneAlias(c.Aliases[i])
			return &clone
		}
	}
	return nil
}

// FindProvidersByModel returns enabled providers whose Models exactly contain
// model, ordered by the full provider priority list.
func (c *Config) FindProvidersByModel(model string) []Provider {
	c.mu.RLock()
	defer c.mu.RUnlock()
	model = strings.TrimSpace(model)
	if model == "" {
		return nil
	}
	matched := make(map[string]Provider, len(c.Providers))
	for _, p := range c.Providers {
		if !p.IsEnabled() {
			continue
		}
		found := false
		for _, g := range p.Groups {
			if providerModelsContain(g.Models, model) {
				found = true
				break
			}
		}
		if !found {
			continue
		}
		matched[p.ID] = cloneProvider(p)
	}
	if len(matched) == 0 {
		return nil
	}
	order := c.providerPriorityOrderLocked()
	out := make([]Provider, 0, len(matched))
	for _, id := range order {
		if p, ok := matched[id]; ok {
			out = append(out, p)
		}
	}
	return out
}

// SetProviderPriority sets the provider priority list. Unknown IDs are ignored,
// duplicates are dropped, and any remaining providers are appended in current
// config order. Unlocked auto-generated alias targets are reordered immediately.
func (c *Config) SetProviderPriority(ids []string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.ProviderPriority = c.normalizeProviderPriorityLocked(ids)
	c.reorderUnlockedAutoAliasTargetsLocked()
}

// ProviderPriorityOrder returns the full priority list, including providers not
// explicitly listed in ProviderPriority.
func (c *Config) ProviderPriorityOrder() []string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.providerPriorityOrderLocked()
}

// IsAutoAliasEnabled reports whether automatic alias generation is enabled.
// Defaults to true via Default() / Load().
func (c *Config) IsAutoAliasEnabled() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.AutoAliasEnabled
}

// SetAutoAliasEnabled sets the global automatic alias generation switch.
func (c *Config) SetAutoAliasEnabled(enabled bool) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.AutoAliasEnabled = enabled
}

// LockAutoAlias marks an auto-generated alias as locked so automatic generation
// and cleanup no longer modify it. The alias remains AutoGenerated=true.
// Returns a clone of the locked alias.
func (c *Config) LockAutoAlias(name string) (Alias, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	name = strings.TrimSpace(name)
	if name == "" {
		return Alias{}, fmt.Errorf("alias name is required")
	}
	idx := c.findAliasIndexLocked(name)
	if idx < 0 {
		return Alias{}, fmt.Errorf("alias %q not found", name)
	}
	a := &c.Aliases[idx]
	if !a.AutoGenerated {
		return Alias{}, fmt.Errorf("alias %q is not auto-generated", name)
	}
	a.Locked = true
	return cloneAlias(*a), nil
}

// AutoGenerateAliases creates or updates unlocked auto-generated aliases for each
// enabled Provider Group's models. Targets use the precise triple
// (provider, group, model); same model in different groups remains independent.
// Manual and locked aliases are left untouched. Disabled providers, disabled
// groups, and auto-alias switches (global or per-provider) produce zero changes.
func (c *Config) AutoGenerateAliases(provider Provider) (created []string, updated []string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if !c.AutoAliasEnabled || !provider.EffectiveAutoAliasEnabled() || provider.Disabled {
		return nil, nil
	}
	providerID := strings.TrimSpace(provider.ID)
	if providerID == "" {
		return nil, nil
	}
	createdSet := map[string]bool{}
	updatedSet := map[string]bool{}
	for _, group := range provider.Groups {
		if group.Disabled {
			continue
		}
		groupID := strings.TrimSpace(group.ID)
		if groupID == "" {
			continue
		}
		protocol := NormalizeProviderProtocol(group.Protocol)
		for _, model := range group.Models {
			model = strings.TrimSpace(model)
			if model == "" {
				continue
			}
			idx := c.findAliasIndexLocked(model)
			if idx < 0 {
				alias := Alias{
					Alias:         model,
					Protocol:      protocol,
					Enabled:       true,
					AutoGenerated: true,
					Targets: []Target{{
						Provider:      providerID,
						Group:         groupID,
						Model:         model,
						Enabled:       true,
						AutoGenerated: true,
					}},
				}
				c.Aliases = append(c.Aliases, cloneAlias(alias))
				if !createdSet[model] {
					createdSet[model] = true
					created = append(created, model)
				}
				continue
			}
			a := &c.Aliases[idx]
			if !a.AutoGenerated || a.Locked {
				continue
			}
			if !ProtocolsMatch(a.Protocol, protocol) {
				continue
			}
			if targetExists(a.Targets, providerID, groupID, model) {
				continue
			}
			a.Targets = append(a.Targets, Target{
				Provider:      providerID,
				Group:         groupID,
				Model:         model,
				Enabled:       true,
				AutoGenerated: true,
			})
			a.Targets = c.sortTargetsByPriorityLocked(a.Targets)
			if !updatedSet[model] && !createdSet[model] {
				updatedSet[model] = true
				updated = append(updated, model)
			}
		}
	}
	return created, updated
}

// ReconcileProviderGroupAutoTargets removes stale system-owned targets for one
// trusted group catalog. Manual aliases, locked aliases, and manual targets are preserved.
func (c *Config) ReconcileProviderGroupAutoTargets(providerID, groupID string, models []string) (removed []string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	providerID = strings.TrimSpace(providerID)
	groupID = strings.TrimSpace(groupID)
	if providerID == "" || groupID == "" {
		return nil
	}
	allowed := make(map[string]bool, len(models))
	for _, model := range models {
		if model = strings.TrimSpace(model); model != "" {
			allowed[model] = true
		}
	}
	aliases := make([]Alias, 0, len(c.Aliases))
	for _, alias := range c.Aliases {
		if !alias.AutoGenerated || alias.Locked {
			aliases = append(aliases, alias)
			continue
		}
		targets := alias.Targets[:0]
		changed := false
		for _, target := range alias.Targets {
			stale := target.AutoGenerated && target.Provider == providerID &&
				strings.TrimSpace(target.Group) == groupID && !allowed[strings.TrimSpace(target.Model)]
			if stale {
				changed = true
				continue
			}
			targets = append(targets, target)
		}
		alias.Targets = targets
		if changed {
			removed = append(removed, alias.Alias)
		}
		if len(alias.Targets) > 0 {
			aliases = append(aliases, alias)
		}
	}
	c.Aliases = aliases
	return removed
}

// RemoveProviderAutoTargets removes targets for providerID from unlocked
// auto-generated aliases. Aliases left with no targets are deleted; their names
// are returned in emptied. Manual aliases are not modified.
func (c *Config) RemoveProviderAutoTargets(providerID string) (emptied []string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	providerID = strings.TrimSpace(providerID)
	if providerID == "" {
		return nil
	}
	next := c.Aliases[:0]
	for i := range c.Aliases {
		a := c.Aliases[i]
		if !a.AutoGenerated || a.Locked {
			next = append(next, a)
			continue
		}
		kept := a.Targets[:0]
		for _, t := range a.Targets {
			if t.Provider == providerID {
				continue
			}
			kept = append(kept, t)
		}
		a.Targets = kept
		if len(a.Targets) == 0 {
			emptied = append(emptied, a.Alias)
			continue
		}
		next = append(next, a)
	}
	// Ensure Aliases is never nil-slice vs empty inconsistency if all removed.
	if len(next) == 0 {
		c.Aliases = []Alias{}
	} else {
		c.Aliases = next
	}
	return emptied
}

// RemoveGroupAutoTargets removes system-owned targets for (providerID, groupID)
// from unlocked auto-generated aliases. Aliases left with no targets are deleted;
// their names are returned in emptied. Manual and locked aliases are not modified.
// Does not rebind to default or sibling groups.
func (c *Config) RemoveGroupAutoTargets(providerID, groupID string) (emptied []string) {
	c.mu.Lock()
	defer c.mu.Unlock()
	providerID = strings.TrimSpace(providerID)
	groupID = strings.TrimSpace(groupID)
	if providerID == "" || groupID == "" {
		return nil
	}
	next := c.Aliases[:0]
	for i := range c.Aliases {
		a := c.Aliases[i]
		if !a.AutoGenerated || a.Locked {
			next = append(next, a)
			continue
		}
		kept := a.Targets[:0]
		for _, t := range a.Targets {
			tg := strings.TrimSpace(t.Group)
			// Only clear system-owned targets for the precise group; protect manual targets.
			if t.Provider == providerID && tg == groupID && t.AutoGenerated {
				continue
			}
			kept = append(kept, t)
		}
		a.Targets = kept
		if len(a.Targets) == 0 {
			emptied = append(emptied, a.Alias)
			continue
		}
		next = append(next, a)
	}
	if len(next) == 0 {
		c.Aliases = []Alias{}
	} else {
		c.Aliases = next
	}
	return emptied
}

func (c *Config) findAliasIndexLocked(name string) int {
	for i := range c.Aliases {
		if c.Aliases[i].Alias == name {
			return i
		}
	}
	return -1
}

func (c *Config) providerPriorityOrderLocked() []string {
	return c.normalizeProviderPriorityLocked(c.ProviderPriority)
}

func (c *Config) normalizeProviderPriorityLocked(ids []string) []string {
	known := make(map[string]bool, len(c.Providers))
	for _, p := range c.Providers {
		if p.ID == "" {
			continue
		}
		known[p.ID] = true
	}
	seen := make(map[string]bool, len(c.Providers))
	out := make([]string, 0, len(c.Providers))
	for _, id := range ids {
		id = strings.TrimSpace(id)
		if id == "" || !known[id] || seen[id] {
			continue
		}
		seen[id] = true
		out = append(out, id)
	}
	for _, p := range c.Providers {
		if p.ID == "" || seen[p.ID] {
			continue
		}
		seen[p.ID] = true
		out = append(out, p.ID)
	}
	return out
}

func (c *Config) reorderUnlockedAutoAliasTargetsLocked() {
	for i := range c.Aliases {
		a := &c.Aliases[i]
		if !a.AutoGenerated || a.Locked {
			continue
		}
		a.Targets = c.sortTargetsByPriorityLocked(a.Targets)
	}
}

func (c *Config) sortTargetsByPriorityLocked(targets []Target) []Target {
	if len(targets) <= 1 {
		return cloneTargets(targets)
	}
	order := c.providerPriorityOrderLocked()
	rank := make(map[string]int, len(order))
	for i, id := range order {
		rank[id] = i
	}
	out := cloneTargets(targets)
	sort.SliceStable(out, func(i, j int) bool {
		ri, oki := rank[out[i].Provider]
		rj, okj := rank[out[j].Provider]
		if !oki {
			ri = len(order)
		}
		if !okj {
			rj = len(order)
		}
		if ri != rj {
			return ri < rj
		}
		// Same provider: keep independent group targets ordered stably by group then model.
		// Empty group is not rewritten to default (fail closed; only v1 decoder injects default).
		gi := strings.TrimSpace(out[i].Group)
		gj := strings.TrimSpace(out[j].Group)
		if gi != gj {
			return gi < gj
		}
		return out[i].Model < out[j].Model
	})
	return out
}

func providerModelsContain(models []string, model string) bool {
	for _, item := range models {
		if item == model {
			return true
		}
	}
	return false
}

func targetExists(targets []Target, providerID, groupID, model string) bool {
	groupID = strings.TrimSpace(groupID)
	for _, t := range targets {
		tg := strings.TrimSpace(t.Group)
		if t.Provider == providerID && tg == groupID && t.Model == model {
			return true
		}
	}
	return false
}

// UpsertAlias adds or replaces an alias.
func (c *Config) UpsertAlias(a Alias) {
	c.mu.Lock()
	defer c.mu.Unlock()
	a.Protocol = NormalizeAliasProtocol(a.Protocol)
	cloned := cloneAlias(a)
	for i := range c.Aliases {
		if c.Aliases[i].Alias == a.Alias {
			c.Aliases[i] = cloned
			return
		}
	}
	c.Aliases = append(c.Aliases, cloned)
}

// RemoveAlias deletes an alias.
func (c *Config) RemoveAlias(name string) bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	for i := range c.Aliases {
		if c.Aliases[i].Alias == name {
			c.Aliases = append(c.Aliases[:i], c.Aliases[i+1:]...)
			return true
		}
	}
	return false
}

// RequestRewriteRulesSnapshot returns request rewrite rules in configured order.
func (c *Config) RequestRewriteRulesSnapshot() []RequestRewriteRule {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return cloneRequestRewriteRules(c.RequestRewriteRules)
}

// FindRequestRewriteRule returns the request rewrite rule with matching name.
func (c *Config) FindRequestRewriteRule(name string) *RequestRewriteRule {
	c.mu.RLock()
	defer c.mu.RUnlock()
	name = strings.TrimSpace(name)
	for i := range c.RequestRewriteRules {
		if c.RequestRewriteRules[i].Name == name {
			clone := cloneRequestRewriteRule(c.RequestRewriteRules[i])
			return &clone
		}
	}
	return nil
}

// UpsertRequestRewriteRule adds or replaces a request rewrite rule by name.
func (c *Config) UpsertRequestRewriteRule(rule RequestRewriteRule) {
	c.mu.Lock()
	defer c.mu.Unlock()
	rule = normalizeRequestRewriteRule(rule)
	for i := range c.RequestRewriteRules {
		if c.RequestRewriteRules[i].Name == rule.Name {
			c.RequestRewriteRules[i] = rule
			return
		}
	}
	c.RequestRewriteRules = append(c.RequestRewriteRules, rule)
}

// SetRequestRewriteRuleEnabled toggles one request rewrite rule.
func (c *Config) SetRequestRewriteRuleEnabled(name string, enabled bool) bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	name = strings.TrimSpace(name)
	for i := range c.RequestRewriteRules {
		if c.RequestRewriteRules[i].Name == name {
			c.RequestRewriteRules[i].Enabled = enabled
			return true
		}
	}
	return false
}

// RemoveRequestRewriteRule deletes a request rewrite rule by name.
func (c *Config) RemoveRequestRewriteRule(name string) bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	name = strings.TrimSpace(name)
	for i := range c.RequestRewriteRules {
		if c.RequestRewriteRules[i].Name == name {
			c.RequestRewriteRules = append(c.RequestRewriteRules[:i], c.RequestRewriteRules[i+1:]...)
			return true
		}
	}
	return false
}

// ReorderRequestRewriteRules replaces rewrite rule order while preserving rule state.
func (c *Config) ReorderRequestRewriteRules(names []string) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if len(names) != len(c.RequestRewriteRules) {
		return fmt.Errorf("request rewrite rule reorder count mismatch: got %d, want %d", len(names), len(c.RequestRewriteRules))
	}
	byName := make(map[string]RequestRewriteRule, len(c.RequestRewriteRules))
	for _, rule := range c.RequestRewriteRules {
		name := strings.TrimSpace(rule.Name)
		if _, exists := byName[name]; exists {
			return fmt.Errorf("duplicate request rewrite rule %q", name)
		}
		byName[name] = rule
	}
	seen := make(map[string]bool, len(names))
	next := make([]RequestRewriteRule, 0, len(names))
	for _, name := range names {
		name = strings.TrimSpace(name)
		if name == "" {
			return fmt.Errorf("request rewrite rule name is required")
		}
		if seen[name] {
			return fmt.Errorf("duplicate request rewrite rule %q in reorder request", name)
		}
		rule, ok := byName[name]
		if !ok {
			return fmt.Errorf("request rewrite rule %q not found", name)
		}
		seen[name] = true
		next = append(next, rule)
	}
	c.RequestRewriteRules = next
	return nil
}

// ApplyRequestRewriteRules is a legacy wrapper that applies rewrite rules for the
// default group. Prefer ApplyRequestRewriteRulesForGroup with an explicit group.
func (c *Config) ApplyRequestRewriteRules(aliasName, provider, model string, payload map[string]any) {
	c.ApplyRequestRewriteRulesForGroup(aliasName, provider, DefaultGroupID, model, payload)
}

// ApplyRequestRewriteRulesForGroup applies rewrite rules for a resolved (provider, group, model).
func (c *Config) ApplyRequestRewriteRulesForGroup(aliasName, provider, group, model string, payload map[string]any) {
	if payload == nil {
		return
	}
	c.mu.RLock()
	rules := cloneRequestRewriteRules(c.RequestRewriteRules)
	c.mu.RUnlock()
	ApplyRequestRewriteRules(payload, aliasName, provider, group, model, rules)
}

func requestRewriteRuleMatches(rule RequestRewriteRule, aliasName, provider, group string) bool {
	if rule.Alias == "" {
		return false
	}
	if rule.Alias != aliasName {
		return false
	}
	group = strings.TrimSpace(group)
	if group == "" {
		return false
	}
	if rule.ProviderGroups == nil || len(rule.ProviderGroups) == 0 {
		return true
	}
	for _, selector := range rule.ProviderGroups {
		if strings.TrimSpace(selector.Provider) == provider && strings.TrimSpace(selector.Group) == group {
			return true
		}
	}
	return false
}

// AddTarget appends a target to an alias; creates alias if missing.
func (c *Config) AddTarget(alias string, t Target) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	t.Group = strings.TrimSpace(t.Group)
	if t.Group == "" {
		return fmt.Errorf("target group is required")
	}
	for i := range c.Aliases {
		if c.Aliases[i].Alias == alias {
			// prevent exact duplicate
			for _, x := range c.Aliases[i].Targets {
				xg := strings.TrimSpace(x.Group)
				if x.Provider == t.Provider && xg == t.Group && x.Model == t.Model {
					return fmt.Errorf("target %s/%s/%s already bound to alias %s", t.Provider, t.Group, t.Model, alias)
				}
			}
			c.Aliases[i].Targets = append(c.Aliases[i].Targets, t)
			return nil
		}
	}
	return fmt.Errorf("alias %q not found", alias)
}

// RemoveTarget is a legacy wrapper that removes a target from the default group.
// Prefer RemoveTargetFromGroup with an explicit group.
func (c *Config) RemoveTarget(alias, provider, model string) error {
	return c.RemoveTargetFromGroup(alias, provider, DefaultGroupID, model)
}

// RemoveTargetFromGroup removes a target by provider+group+model.
func (c *Config) RemoveTargetFromGroup(alias, provider, group, model string) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	group = strings.TrimSpace(group)
	if group == "" {
		return fmt.Errorf("target group is required")
	}
	for i := range c.Aliases {
		if c.Aliases[i].Alias != alias {
			continue
		}
		out := c.Aliases[i].Targets[:0]
		found := false
		for _, t := range c.Aliases[i].Targets {
			tg := strings.TrimSpace(t.Group)
			if t.Provider == provider && tg == group && t.Model == model {
				found = true
				continue
			}
			out = append(out, t)
		}
		if !found {
			return fmt.Errorf("target %s/%s/%s not found on alias %s", provider, group, model, alias)
		}
		c.Aliases[i].Targets = out
		return nil
	}
	return fmt.Errorf("alias %q not found", alias)
}

// ReorderTargets replaces an alias target order while preserving target state.
func (c *Config) ReorderTargets(alias string, refs []TargetRef) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	for i := range c.Aliases {
		if c.Aliases[i].Alias != alias {
			continue
		}
		current := c.Aliases[i].Targets
		if len(refs) != len(current) {
			return fmt.Errorf("alias %s reorder target count mismatch: got %d, want %d", alias, len(refs), len(current))
		}
		byRef := make(map[TargetRef]Target, len(current))
		for _, target := range current {
			group := strings.TrimSpace(target.Group)
			if group == "" {
				return fmt.Errorf("alias %s has target without group", alias)
			}
			ref := TargetRef{Provider: target.Provider, Group: group, Model: target.Model}
			if _, exists := byRef[ref]; exists {
				return fmt.Errorf("alias %s has duplicate target %s/%s/%s", alias, target.Provider, group, target.Model)
			}
			byRef[ref] = target
		}
		seen := make(map[TargetRef]bool, len(refs))
		next := make([]Target, 0, len(refs))
		for _, ref := range refs {
			ref.Provider = strings.TrimSpace(ref.Provider)
			ref.Group = strings.TrimSpace(ref.Group)
			ref.Model = strings.TrimSpace(ref.Model)
			if ref.Provider == "" || ref.Group == "" || ref.Model == "" {
				return fmt.Errorf("target provider, group and model are required")
			}
			if seen[ref] {
				return fmt.Errorf("duplicate target %s/%s/%s in reorder request", ref.Provider, ref.Group, ref.Model)
			}
			target, ok := byRef[ref]
			if !ok {
				return fmt.Errorf("target %s/%s/%s not found on alias %s", ref.Provider, ref.Group, ref.Model, alias)
			}
			seen[ref] = true
			next = append(next, target)
		}
		c.Aliases[i].Targets = next
		return nil
	}
	return fmt.Errorf("alias %q not found", alias)
}

// AvailableTargets returns alias targets that are individually enabled and point
// at providers that still exist and are enabled.
func (c *Config) AvailableTargets(alias Alias) []Target {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.availableTargetsLocked(alias)
}

func (c *Config) availableTargetsLocked(alias Alias) []Target {
	targets := make([]Target, 0, len(alias.Targets))
	for _, t := range alias.Targets {
		if !t.Enabled {
			continue
		}
		provider := c.findProviderLocked(t.Provider)
		if provider == nil || !provider.IsEnabled() {
			continue
		}
		view := cloneProvider(*provider)
		groupID := strings.TrimSpace(t.Group)
		if groupID == "" {
			continue
		}
		group := view.FindGroup(groupID)
		if group == nil || !group.IsEnabled() {
			continue
		}
		if !ProtocolsMatch(alias.Protocol, group.Protocol) {
			continue
		}
		targets = append(targets, t)
	}
	return targets
}

// AvailableAliasNames returns alias names that are enabled and still have at
// least one routable target after provider availability is applied.
func (c *Config) AvailableAliasNames() []string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.availableAliasNamesLocked("")
}

// AvailableAliasNamesForProtocol returns enabled alias names for one protocol.
func (c *Config) AvailableAliasNamesForProtocol(protocol string) []string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.availableAliasNamesLocked(protocol)
}

func (c *Config) availableAliasNamesLocked(protocol string) []string {
	names := make([]string, 0, len(c.Aliases))
	for _, a := range c.Aliases {
		if !a.Enabled {
			continue
		}
		if protocol != "" && NormalizeAliasProtocol(a.Protocol) != NormalizeAliasProtocol(protocol) {
			continue
		}
		if len(c.availableTargetsLocked(a)) == 0 {
			continue
		}
		names = append(names, a.Alias)
	}
	return names
}

// Validate returns structural issues plus reference/availability checks used by
// StartProxy, Doctor, and other strict consumers.
func (c *Config) Validate() []error {
	return c.validate(true)
}

// ValidateForPersist returns only structural issues that must block ConfigStore
// commits. Dangling provider refs and "no available targets" stay as diagnostics
// (and lifecycle plans), not unconditional hard blocks on every write.
func (c *Config) ValidateForPersist() []error {
	return c.validate(false)
}

func (c *Config) validate(strictRefs bool) []error {
	c.mu.RLock()
	defer c.mu.RUnlock()
	var errs []error
	ids := map[string]bool{}
	for i := range c.Providers {
		p := cloneProvider(c.Providers[i])
		normalizeProviderGroups(p.Groups)
		if p.ID == "" {
			errs = append(errs, fmt.Errorf("provider with empty id"))
			continue
		}
		if ids[p.ID] {
			errs = append(errs, fmt.Errorf("duplicate provider id %q", p.ID))
		}
		ids[p.ID] = true
		if p.BaseURL == "" {
			if len(p.EffectiveBaseURLs()) == 0 {
				errs = append(errs, fmt.Errorf("provider %q missing base_url", p.ID))
				continue
			}
		}
		if len(p.Groups) == 0 {
			errs = append(errs, fmt.Errorf("provider %q has no groups", p.ID))
			continue
		}
		// Base URL validation uses the first group's protocol when available.
		baseProtocol := DefaultProviderProtocol()
		if len(p.Groups) > 0 {
			baseProtocol = NormalizeProviderProtocol(p.Groups[0].Protocol)
		}
		if err := ValidateProviderBaseURLs(baseProtocol, p.BaseURL, p.BaseURLs); err != nil {
			errs = append(errs, fmt.Errorf("provider %q %s", p.ID, err))
		}
		if err := ValidateProviderBaseURLStrategy(p.BaseURLStrategy); err != nil {
			errs = append(errs, fmt.Errorf("provider %q %s", p.ID, err))
		}
		if err := providerSharedHeadersConflictWithProtocols(p); err != nil {
			errs = append(errs, err)
		}
		groupIDs := map[string]bool{}
		for _, g := range p.Groups {
			g.Protocol = NormalizeProviderProtocol(g.Protocol)
			if strings.TrimSpace(g.ID) == "" {
				errs = append(errs, fmt.Errorf("provider %q has group with empty id", p.ID))
				continue
			}
			if groupIDs[g.ID] {
				errs = append(errs, fmt.Errorf("provider %q has duplicate group id %q", p.ID, g.ID))
			}
			groupIDs[g.ID] = true
			if err := ValidateProtocol(g.Protocol); err != nil {
				errs = append(errs, fmt.Errorf("provider %q group %q %s", p.ID, g.ID, err))
			}
			seenAPIKeys := map[string]bool{}
			for _, apiKey := range g.APIKeys {
				trimmed := strings.TrimSpace(apiKey)
				if trimmed == "" {
					errs = append(errs, fmt.Errorf("provider %q group %q has empty api_keys entry", p.ID, g.ID))
					continue
				}
				if seenAPIKeys[trimmed] {
					errs = append(errs, fmt.Errorf("provider %q group %q has duplicate api_keys entry", p.ID, g.ID))
					continue
				}
				seenAPIKeys[trimmed] = true
			}
			seenModels := map[string]bool{}
			for _, model := range g.Models {
				trimmed := strings.TrimSpace(model)
				if trimmed == "" {
					errs = append(errs, fmt.Errorf("provider %q group %q has empty model entry", p.ID, g.ID))
					continue
				}
				if seenModels[trimmed] {
					errs = append(errs, fmt.Errorf("provider %q group %q has duplicate model %q", p.ID, g.ID, trimmed))
					continue
				}
				seenModels[trimmed] = true
			}
			validModelsSource := g.ModelsSource == "" || g.ModelsSource == "discovered" || g.ModelsSource == "imported" || g.ModelsSource == "manual"
			if !validModelsSource {
				errs = append(errs, fmt.Errorf("provider %q group %q has invalid models_source %q", p.ID, g.ID, g.ModelsSource))
			}
			if validModelsSource && g.ModelsSource != "" && len(g.Models) == 0 {
				errs = append(errs, fmt.Errorf("provider %q group %q has models_source %q but no models", p.ID, g.ID, g.ModelsSource))
			}
		}
	}
	seen := map[string]bool{}
	for _, a := range c.Aliases {
		a.Protocol = NormalizeAliasProtocol(a.Protocol)
		if a.Alias == "" {
			errs = append(errs, fmt.Errorf("alias with empty name"))
			continue
		}
		if seen[a.Alias] {
			errs = append(errs, fmt.Errorf("duplicate alias %q", a.Alias))
		}
		seen[a.Alias] = true
		if err := ValidateProtocol(a.Protocol); err != nil {
			errs = append(errs, fmt.Errorf("alias %q %s", a.Alias, err))
		}
		for _, t := range a.Targets {
			groupID := strings.TrimSpace(t.Group)
			if groupID == "" {
				errs = append(errs, fmt.Errorf("alias %q target %s/%s requires group", a.Alias, t.Provider, t.Model))
				continue
			}
			if t.Provider == "" || t.Model == "" {
				errs = append(errs, fmt.Errorf("alias %q has malformed target", a.Alias))
				continue
			}
			if !ids[t.Provider] {
				if strictRefs {
					errs = append(errs, fmt.Errorf("alias %q references unknown provider %q", a.Alias, t.Provider))
				}
				continue
			}
			provider := c.findProviderLocked(t.Provider)
			if provider == nil {
				continue
			}
			view := cloneProvider(*provider)
			group := view.FindGroup(groupID)
			if group == nil {
				if strictRefs {
					errs = append(errs, fmt.Errorf("alias %q target %s/%s references unknown group %q", a.Alias, t.Provider, t.Model, groupID))
				}
				continue
			}
			if !ProtocolsMatch(a.Protocol, group.Protocol) {
				// Protocol mismatch is structural/illegal identity for routing.
				errs = append(errs, fmt.Errorf("alias %q target %s/%s/%s protocol %q does not match group protocol %q", a.Alias, t.Provider, groupID, t.Model, a.Protocol, NormalizeProviderProtocol(group.Protocol)))
			}
		}
		if strictRefs {
			enabled := len(c.availableTargetsLocked(a))
			if a.Enabled && enabled == 0 {
				errs = append(errs, fmt.Errorf("alias %q has no available targets", a.Alias))
			}
		}
	}
	rewriteNames := map[string]bool{}
	for _, rule := range c.RequestRewriteRules {
		rule = normalizeRequestRewriteRule(rule)
		if rule.Name == "" {
			errs = append(errs, fmt.Errorf("request rewrite rule with empty name"))
			continue
		}
		if rewriteNames[rule.Name] {
			errs = append(errs, fmt.Errorf("duplicate request rewrite rule %q", rule.Name))
		}
		rewriteNames[rule.Name] = true
		if RequestRewriteRuleUsesLegacySyntax(rule) {
			continue
		}
		if rule.Alias == "" {
			errs = append(errs, fmt.Errorf("request rewrite rule %q requires alias", rule.Name))
		}
		if len(rule.Ops) == 0 {
			errs = append(errs, fmt.Errorf("request rewrite rule %q requires ops", rule.Name))
		}
		for _, err := range validateRequestRewriteOperations(rule) {
			errs = append(errs, err)
		}
		for _, sel := range rule.ProviderGroups {
			if strings.TrimSpace(sel.Provider) == "" || strings.TrimSpace(sel.Group) == "" {
				errs = append(errs, fmt.Errorf("request rewrite rule %q has malformed provider/group selector", rule.Name))
			}
		}
	}
	if c.Server.Port <= 0 || c.Server.Port > 65535 {
		errs = append(errs, fmt.Errorf("invalid server port %d", c.Server.Port))
	}
	if !isLoopbackHost(c.Server.Host) && (strings.TrimSpace(c.Server.APIKey) == "" || c.Server.APIKey == DefaultLocalAPIKey) {
		errs = append(errs, fmt.Errorf("server.api_key must be non-empty and non-default when listening on non-loopback host %q", c.Server.Host))
	}
	if c.Admin.Port < 0 || c.Admin.Port > 65535 {
		errs = append(errs, fmt.Errorf("invalid admin port %d", c.Admin.Port))
	}
	if c.Server.ConnectTimeoutMs <= 0 {
		errs = append(errs, fmt.Errorf("server.connect_timeout_ms must be greater than 0"))
	}
	if c.Server.ResponseHeaderTimeoutMs <= 0 {
		errs = append(errs, fmt.Errorf("server.response_header_timeout_ms must be greater than 0"))
	}
	if c.Server.FirstByteTimeoutMs <= 0 {
		errs = append(errs, fmt.Errorf("server.first_byte_timeout_ms must be greater than 0"))
	}
	if c.Server.RequestReadTimeoutMs <= 0 {
		errs = append(errs, fmt.Errorf("server.request_read_timeout_ms must be greater than 0"))
	}
	if c.Server.StreamIdleTimeoutMs <= 0 {
		errs = append(errs, fmt.Errorf("server.stream_idle_timeout_ms must be greater than 0"))
	}
	if c.Server.StreamPrecommitBufferMs < 0 {
		errs = append(errs, fmt.Errorf("server.stream_precommit_buffer_ms must be greater than or equal to 0"))
	}
	if err := ValidateFailoverStatusCodes(c.Server.FailoverStatusCodes); err != nil {
		errs = append(errs, err)
	}
	if err := routing.ValidateConfig(c.Server.Routing); err != nil {
		errs = append(errs, err)
	}
	return errs
}

func normalizeAdmin(admin *Admin) {
	if admin == nil {
		return
	}
	if strings.TrimSpace(admin.Host) == "" {
		admin.Host = "127.0.0.1"
	}
	if admin.Port == 0 {
		admin.Port = 9983
	}
}

func normalizeServerTimeouts(server *Server) {
	if server == nil {
		return
	}
	server.ConnectTimeoutMs = normalizeServerTimeoutMs(server.ConnectTimeoutMs, DefaultConnectTimeoutMs)
	server.ResponseHeaderTimeoutMs = normalizeServerTimeoutMs(server.ResponseHeaderTimeoutMs, DefaultResponseHeaderTimeoutMs)
	server.FirstByteTimeoutMs = normalizeServerTimeoutMs(server.FirstByteTimeoutMs, DefaultFirstByteTimeoutMs)
	server.RequestReadTimeoutMs = normalizeServerTimeoutMs(server.RequestReadTimeoutMs, DefaultRequestReadTimeoutMs)
	server.StreamIdleTimeoutMs = normalizeServerTimeoutMs(server.StreamIdleTimeoutMs, DefaultStreamIdleTimeoutMs)
	server.StreamPrecommitBufferMs = normalizeServerNonNegativeMs(server.StreamPrecommitBufferMs, DefaultStreamPrecommitBufferMs)
}

func normalizeServerFailoverStatusCodes(server *Server) {
	if server == nil {
		return
	}
	server.FailoverStatusCodes = NormalizeFailoverStatusCodes(server.FailoverStatusCodes)
}

func NormalizeFailoverStatusCodes(statusCodes []int) []int {
	if statusCodes == nil {
		return DefaultFailoverStatusCodes()
	}
	if len(statusCodes) == 0 {
		return []int{}
	}
	seen := map[int]bool{}
	out := make([]int, 0, len(statusCodes))
	for _, statusCode := range statusCodes {
		if seen[statusCode] {
			continue
		}
		seen[statusCode] = true
		out = append(out, statusCode)
	}
	slices.Sort(out)
	return out
}

func ValidateFailoverStatusCodes(statusCodes []int) error {
	for _, statusCode := range statusCodes {
		if statusCode < 100 || statusCode > 599 {
			return fmt.Errorf("server.failover_status_codes must contain HTTP status codes from 100 to 599")
		}
	}
	return nil
}

func normalizeServerRouting(server *Server) {
	if server == nil {
		return
	}
	server.Routing = routing.NormalizeConfig(server.Routing)
	if _, err := routing.ResolveParams(server.Routing); err != nil {
		server.Routing = routing.NormalizeConfig(routing.Config{Strategy: routing.DefaultStrategy})
	}
}

func normalizeServerTimeoutMs(value int, fallback int) int {
	if value <= 0 {
		return fallback
	}
	return value
}

func normalizeServerNonNegativeMs(value int, fallback int) int {
	if value < 0 {
		return fallback
	}
	return value
}
func isLoopbackHost(host string) bool {
	host = strings.TrimSpace(host)
	if host == "" || strings.EqualFold(host, "localhost") {
		return true
	}
	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback()
}

func cloneProvider(p Provider) Provider {
	p.BaseURLStrategy = NormalizeProviderBaseURLStrategy(p.BaseURLStrategy)
	baseURLs := NormalizeProviderBaseURLs(p.BaseURL, p.BaseURLs)
	if len(baseURLs) > 0 {
		p.BaseURL = baseURLs[0]
	}
	if len(baseURLs) > 1 {
		p.BaseURLs = cloneStrings(baseURLs)
	} else {
		p.BaseURLs = nil
	}
	p.Headers = cloneStringMap(p.Headers)
	p.Groups = cloneProviderGroups(p.Groups)
	normalizeProviderGroups(p.Groups)
	if p.AutoAliasEnabled != nil {
		v := *p.AutoAliasEnabled
		p.AutoAliasEnabled = &v
	}
	return p
}

func cloneAlias(a Alias) Alias {
	a.Protocol = NormalizeAliasProtocol(a.Protocol)
	a.Targets = cloneTargets(a.Targets)
	return a
}

func normalizeProviders(providers []Provider) {
	for i := range providers {
		providers[i].BaseURLStrategy = NormalizeProviderBaseURLStrategy(providers[i].BaseURLStrategy)
		baseURLs := NormalizeProviderBaseURLs(providers[i].BaseURL, providers[i].BaseURLs)
		if len(baseURLs) > 0 {
			providers[i].BaseURL = baseURLs[0]
		} else {
			providers[i].BaseURL = NormalizeProviderBaseURL(providers[i].BaseURL)
		}
		if len(baseURLs) > 1 {
			providers[i].BaseURLs = cloneStrings(baseURLs)
		} else {
			providers[i].BaseURLs = nil
		}
		normalizeProviderGroups(providers[i].Groups)
	}
}

// ProviderBaseURLsEqual compares normalized ordered base URL lists.
func ProviderBaseURLsEqual(a Provider, b Provider) bool {
	return slices.Equal(a.EffectiveBaseURLs(), b.EffectiveBaseURLs())
}

func normalizeAliases(aliases []Alias) {
	for i := range aliases {
		aliases[i].Protocol = NormalizeAliasProtocol(aliases[i].Protocol)
		for j := range aliases[i].Targets {
			aliases[i].Targets[j].Group = strings.TrimSpace(aliases[i].Targets[j].Group)
		}
	}
}

func normalizeRequestRewriteRules(rules []RequestRewriteRule) {
	for i := range rules {
		rules[i] = normalizeRequestRewriteRule(rules[i])
	}
}

func normalizeRequestRewriteRule(rule RequestRewriteRule) RequestRewriteRule {
	rule.Name = strings.TrimSpace(rule.Name)
	rule.Alias = strings.TrimSpace(rule.Alias)
	if rule.ProviderGroups != nil {
		seen := map[string]bool{}
		next := make([]ProviderGroupSelector, 0, len(rule.ProviderGroups))
		for _, sel := range rule.ProviderGroups {
			provider := strings.TrimSpace(sel.Provider)
			group := strings.TrimSpace(sel.Group)
			key := provider + "\x00" + group
			if seen[key] {
				continue
			}
			seen[key] = true
			next = append(next, ProviderGroupSelector{Provider: provider, Group: group})
		}
		// Preserve explicit empty wildcard as non-nil empty slice.
		if len(rule.ProviderGroups) == 0 {
			rule.ProviderGroups = []ProviderGroupSelector{}
		} else {
			rule.ProviderGroups = next
		}
	}
	if len(rule.Set) > 0 {
		next := make(map[string]any, len(rule.Set))
		for key, value := range rule.Set {
			trimmed := strings.TrimSpace(key)
			if trimmed == "" {
				continue
			}
			next[trimmed] = cloneJSONValue(value)
		}
		rule.Set = next
	} else {
		rule.Set = nil
	}
	if len(rule.Delete) > 0 {
		seen := map[string]bool{}
		next := make([]string, 0, len(rule.Delete))
		for _, key := range rule.Delete {
			trimmed := strings.TrimSpace(key)
			if trimmed == "" || seen[trimmed] {
				continue
			}
			seen[trimmed] = true
			next = append(next, trimmed)
		}
		rule.Delete = next
	} else {
		rule.Delete = nil
	}
	if len(rule.Ops) > 0 {
		next := make([]RequestRewriteOperation, 0, len(rule.Ops))
		for _, op := range rule.Ops {
			op = normalizeRequestRewriteOperation(op)
			if op.Op == "" && op.Path == "" {
				continue
			}
			next = append(next, op)
		}
		rule.Ops = next
	} else {
		rule.Ops = nil
	}
	return rule
}

func cloneProviders(in []Provider) []Provider {
	out := make([]Provider, len(in))
	for i := range in {
		out[i] = cloneProvider(in[i])
	}
	return out
}

func cloneAliases(in []Alias) []Alias {
	out := make([]Alias, len(in))
	for i := range in {
		out[i] = cloneAlias(in[i])
	}
	return out
}

func cloneRequestRewriteRules(in []RequestRewriteRule) []RequestRewriteRule {
	if len(in) == 0 {
		return nil
	}
	out := make([]RequestRewriteRule, len(in))
	for i := range in {
		out[i] = cloneRequestRewriteRule(in[i])
	}
	return out
}

func cloneRequestRewriteRule(in RequestRewriteRule) RequestRewriteRule {
	in.ProviderGroups = cloneProviderGroupSelectors(in.ProviderGroups)
	// Preserve explicit empty ProviderGroups wildcard.
	if in.ProviderGroups != nil && len(in.ProviderGroups) == 0 {
		in.ProviderGroups = []ProviderGroupSelector{}
	}
	in.Ops = cloneRequestRewriteOperations(in.Ops)
	in.Set = cloneAnyMap(in.Set)
	in.Delete = cloneStrings(in.Delete)
	return in
}

func cloneTargets(in []Target) []Target {
	out := make([]Target, len(in))
	copy(out, in)
	return out
}

func cloneInts(in []int) []int {
	out := make([]int, len(in))
	copy(out, in)
	return out
}

func cloneStrings(in []string) []string {
	out := make([]string, len(in))
	copy(out, in)
	return out
}

func cloneStringMap(in map[string]string) map[string]string {
	if len(in) == 0 {
		return nil
	}
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func cloneAnyMap(in map[string]any) map[string]any {
	if len(in) == 0 {
		return nil
	}
	out := make(map[string]any, len(in))
	for k, v := range in {
		out[k] = cloneJSONValue(v)
	}
	return out
}

func cloneJSONValue(value any) any {
	switch v := value.(type) {
	case map[string]any:
		return cloneAnyMap(v)
	case []any:
		out := make([]any, len(v))
		for i := range v {
			out[i] = cloneJSONValue(v[i])
		}
		return out
	case []string:
		return cloneStrings(v)
	default:
		return value
	}
}
