package config

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
)

// decodeConfigJSON parses on-disk config bytes into the runtime model.
// schema v1 / missing version migrate into a unique default group in memory only.
func decodeConfigJSON(data []byte) (*Config, error) {
	if len(bytes.TrimSpace(data)) == 0 {
		c := Default()
		return c, nil
	}

	var probe struct {
		SchemaVersion json.RawMessage `json:"schema_version"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}

	version, legacy, err := parseSchemaVersion(probe.SchemaVersion)
	if err != nil {
		return nil, err
	}
	if legacy {
		cfg, err := decodeV1Config(data)
		if err != nil {
			return nil, err
		}
		cfg.SchemaVersion = CurrentSchemaVersion
		cfg.loadedFromLegacy = true
		return cfg, nil
	}
	switch version {
	case CurrentSchemaVersion:
		cfg, err := decodeV2Config(data)
		if err != nil {
			return nil, err
		}
		cfg.SchemaVersion = CurrentSchemaVersion
		cfg.loadedFromLegacy = false
		return cfg, nil
	default:
		return nil, fmt.Errorf("unsupported schema version %d", version)
	}
}

// parseSchemaVersion distinguishes missing (legacy), integer 1/2, and invalid forms.
// missing → legacy=true; null / non-integer / unknown → error.
func parseSchemaVersion(raw json.RawMessage) (version int, legacy bool, err error) {
	if len(raw) == 0 {
		return 0, true, nil
	}
	trimmed := bytes.TrimSpace(raw)
	if bytes.Equal(trimmed, []byte("null")) {
		return 0, false, fmt.Errorf("unsupported schema version")
	}
	// Reject strings/bools/objects/arrays: only JSON number tokens are accepted.
	// (json.Number is a string under the hood and would accept a quoted "2".)
	if len(trimmed) == 0 || (trimmed[0] != '-' && (trimmed[0] < '0' || trimmed[0] > '9')) {
		return 0, false, fmt.Errorf("unsupported schema version")
	}
	dec := json.NewDecoder(bytes.NewReader(trimmed))
	dec.UseNumber()
	var num json.Number
	if err := dec.Decode(&num); err != nil {
		return 0, false, fmt.Errorf("unsupported schema version")
	}
	// Reject floats and non-integer encodings.
	if strings.ContainsAny(num.String(), ".eE") {
		return 0, false, fmt.Errorf("unsupported schema version")
	}
	n, err := num.Int64()
	if err != nil {
		return 0, false, fmt.Errorf("unsupported schema version")
	}
	if n == 1 {
		return 1, true, nil
	}
	if n == int64(CurrentSchemaVersion) {
		return CurrentSchemaVersion, false, nil
	}
	return int(n), false, fmt.Errorf("unsupported schema version %d", n)
}

// --- v1 wire ---

type v1WireConfig struct {
	Server              Server              `json:"server"`
	Admin               Admin               `json:"admin"`
	Desktop             Desktop             `json:"desktop"`
	Providers           []v1WireProvider    `json:"providers"`
	Aliases             []v1WireAlias       `json:"aliases"`
	RequestRewriteRules []v1WireRewriteRule `json:"request_rewrite_rules"`
	ProviderPriority    []string            `json:"provider_priority"`
	AutoAliasEnabled    *bool               `json:"auto_alias_enabled"`
}

type v1WireProvider struct {
	ID               string            `json:"id"`
	Name             string            `json:"name"`
	Protocol         string            `json:"protocol"`
	BaseURL          string            `json:"base_url"`
	BaseURLs         []string          `json:"base_urls"`
	BaseURLStrategy  string            `json:"base_url_strategy"`
	APIKey           string            `json:"api_key"`
	APIKeys          []string          `json:"api_keys"`
	Headers          map[string]string `json:"headers"`
	Models           []string          `json:"models"`
	ModelsSource     string            `json:"models_source"`
	Disabled         bool              `json:"disabled"`
	AutoAliasEnabled *bool             `json:"auto_alias_enabled"`
}

func (p *v1WireProvider) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if _, ok := raw["groups"]; ok {
		id := peekJSONString(raw["id"])
		if id == "" {
			id = "?"
		}
		return fmt.Errorf("mixed schema format: provider %q has groups field under schema v1/legacy", id)
	}
	type plain v1WireProvider
	var out plain
	if err := json.Unmarshal(data, &out); err != nil {
		return err
	}
	*p = v1WireProvider(out)
	return nil
}

type v1WireAlias struct {
	Alias           string         `json:"alias"`
	DisplayName     string         `json:"display_name"`
	Protocol        string         `json:"protocol"`
	Enabled         bool           `json:"enabled"`
	Targets         []v1WireTarget `json:"targets"`
	AutoGenerated   bool           `json:"auto_generated"`
	Locked          bool           `json:"locked"`
	TargetOrderMode string         `json:"target_order_mode"`
}

type v1WireTarget struct {
	Provider      string `json:"provider"`
	Model         string `json:"model"`
	Enabled       bool   `json:"enabled"`
	AutoGenerated bool   `json:"auto_generated"`
}

func (t *v1WireTarget) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	// v2-only field; presence under legacy schema must fail closed (never silently dropped).
	if _, ok := raw["group"]; ok {
		provider := peekJSONString(raw["provider"])
		if provider == "" {
			provider = "?"
		}
		model := peekJSONString(raw["model"])
		if model == "" {
			model = "?"
		}
		return fmt.Errorf("mixed schema format: alias target provider=%q model=%q has group field under schema v1/legacy", provider, model)
	}
	type plain v1WireTarget
	var out plain
	if err := json.Unmarshal(data, &out); err != nil {
		return err
	}
	*t = v1WireTarget(out)
	return nil
}

type v1WireRewriteRule struct {
	Name      string                    `json:"name"`
	Alias     string                    `json:"alias"`
	Providers []string                  `json:"providers"`
	Enabled   bool                      `json:"enabled"`
	Override  bool                      `json:"override"`
	Ops       []RequestRewriteOperation `json:"ops"`
	Set       map[string]any            `json:"set"`
	Delete    []string                  `json:"delete"`

	providersPresent bool
}

func (r *v1WireRewriteRule) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	// v2-only field; presence under legacy schema must fail closed (never silently dropped).
	if _, ok := raw["provider_groups"]; ok {
		name := peekJSONString(raw["name"])
		if name == "" {
			name = "?"
		}
		return fmt.Errorf("mixed schema format: request rewrite rule %q has provider_groups field under schema v1/legacy", name)
	}
	_, r.providersPresent = raw["providers"]
	type plain struct {
		Name      string                    `json:"name"`
		Alias     string                    `json:"alias"`
		Providers []string                  `json:"providers"`
		Enabled   bool                      `json:"enabled"`
		Override  bool                      `json:"override"`
		Ops       []RequestRewriteOperation `json:"ops"`
		Set       map[string]any            `json:"set"`
		Delete    []string                  `json:"delete"`
	}
	var out plain
	if err := json.Unmarshal(data, &out); err != nil {
		return err
	}
	r.Name = out.Name
	r.Alias = out.Alias
	r.Providers = out.Providers
	r.Enabled = out.Enabled
	r.Override = out.Override
	r.Ops = out.Ops
	r.Set = out.Set
	r.Delete = out.Delete
	return nil
}

func decodeV1Config(data []byte) (*Config, error) {
	var wire v1WireConfig
	if err := json.Unmarshal(data, &wire); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	c := Default()
	c.Server = wire.Server
	c.Admin = wire.Admin
	c.Desktop = wire.Desktop
	c.ProviderPriority = cloneStrings(wire.ProviderPriority)
	if wire.AutoAliasEnabled != nil {
		c.AutoAliasEnabled = *wire.AutoAliasEnabled
	}

	providers, providerRefs := migrateV1Providers(wire.Providers)
	c.Providers = providers

	c.Aliases = make([]Alias, 0, len(wire.Aliases))
	for _, wa := range wire.Aliases {
		a := Alias{
			Alias:           wa.Alias,
			DisplayName:     wa.DisplayName,
			Protocol:        wa.Protocol,
			Enabled:         wa.Enabled,
			AutoGenerated:   wa.AutoGenerated,
			Locked:          wa.Locked,
			TargetOrderMode: storageTargetOrderMode(wa.TargetOrderMode),
			Targets:         make([]Target, 0, len(wa.Targets)),
		}
		for _, wt := range wa.Targets {
			provider, group := migrateV1ProviderRef(providerRefs, wt.Provider)
			a.Targets = append(a.Targets, Target{
				Provider:      provider,
				Group:         group,
				Model:         wt.Model,
				Enabled:       wt.Enabled,
				AutoGenerated: wt.AutoGenerated,
			})
		}
		c.Aliases = append(c.Aliases, a)
	}

	c.RequestRewriteRules = make([]RequestRewriteRule, 0, len(wire.RequestRewriteRules))
	for _, wr := range wire.RequestRewriteRules {
		rule := RequestRewriteRule{
			Name:     wr.Name,
			Alias:    wr.Alias,
			Enabled:  wr.Enabled,
			Override: wr.Override,
			Ops:      cloneRequestRewriteOperations(wr.Ops),
			Set:      cloneAnyMap(wr.Set),
			Delete:   cloneStrings(wr.Delete),
		}
		if wr.providersPresent && len(wr.Providers) > 0 {
			seen := map[string]bool{}
			for _, providerID := range wr.Providers {
				providerID = strings.TrimSpace(providerID)
				if providerID == "" || seen[providerID] {
					continue
				}
				seen[providerID] = true
				provider, group := migrateV1ProviderRef(providerRefs, providerID)
				rule.ProviderGroups = append(rule.ProviderGroups, ProviderGroupSelector{
					Provider: provider,
					Group:    group,
				})
			}
		} else {
			// Empty or omitted providers → explicit wildcard (empty provider_groups).
			rule.ProviderGroups = []ProviderGroupSelector{}
		}
		c.RequestRewriteRules = append(c.RequestRewriteRules, rule)
	}
	c.ProviderPriority = migrateV1ProviderPriority(providerRefs, c.ProviderPriority)
	return c, nil
}

type v1ProviderRef struct {
	Provider string
	Group    string
}

type v1ProviderCluster struct {
	base    v1WireProvider
	members []v1WireProvider
}

// migrateV1Providers groups legacy providers which share the complete set of
// provider-level connection settings. The returned refs translate every old
// provider identity to its retained provider and group identity.
func migrateV1Providers(in []v1WireProvider) ([]Provider, map[string]v1ProviderRef) {
	clusters := make([]v1ProviderCluster, 0, len(in))
	for _, wp := range in {
		placed := false
		for i := range clusters {
			if v1ProvidersShareConnection(clusters[i].base, wp) {
				clusters[i].members = append(clusters[i].members, wp)
				placed = true
				break
			}
		}
		if !placed {
			clusters = append(clusters, v1ProviderCluster{base: wp, members: []v1WireProvider{wp}})
		}
	}

	providers := make([]Provider, 0, len(clusters))
	refs := make(map[string]v1ProviderRef, len(in))
	for _, cluster := range clusters {
		base := cluster.base
		p := Provider{
			ID:               base.ID,
			Name:             base.Name,
			BaseURL:          base.BaseURL,
			BaseURLs:         cloneStrings(base.BaseURLs),
			BaseURLStrategy:  base.BaseURLStrategy,
			Headers:          cloneStringMap(base.Headers),
			Disabled:         len(cluster.members) == 1 && base.Disabled,
			AutoAliasEnabled: cloneBoolPtr(base.AutoAliasEnabled),
			Groups:           make([]ProviderGroup, 0, len(cluster.members)),
		}
		usedGroups := map[string]bool{}
		for i, member := range cluster.members {
			groupID := DefaultGroupID
			if i > 0 {
				groupID = legacyProviderGroupID(member.ID, i+1, usedGroups)
			}
			usedGroups[groupID] = true
			groupName := strings.TrimSpace(member.Name)
			if len(cluster.members) == 1 || groupName == "" {
				groupName = DefaultGroupName
			}
			p.Groups = append(p.Groups, ProviderGroup{
				ID:           groupID,
				Name:         groupName,
				Protocol:     member.Protocol,
				APIKey:       member.APIKey,
				APIKeys:      cloneStrings(member.APIKeys),
				Models:       cloneStrings(member.Models),
				ModelsSource: member.ModelsSource,
				Disabled:     len(cluster.members) > 1 && member.Disabled,
			})
			refs[member.ID] = v1ProviderRef{Provider: base.ID, Group: groupID}
		}
		providers = append(providers, p)
	}
	return providers, refs
}

func v1ProvidersShareConnection(a, b v1WireProvider) bool {
	if len(a.BaseURLs) == 0 && len(b.BaseURLs) == 0 &&
		NormalizeProviderBaseURL(a.BaseURL) == "" && NormalizeProviderBaseURL(b.BaseURL) == "" {
		return false
	}
	return reflect.DeepEqual(NormalizeProviderBaseURLs(a.BaseURL, a.BaseURLs), NormalizeProviderBaseURLs(b.BaseURL, b.BaseURLs)) &&
		NormalizeProviderBaseURLStrategy(a.BaseURLStrategy) == NormalizeProviderBaseURLStrategy(b.BaseURLStrategy) &&
		v1ProviderHeadersEqual(a.Headers, b.Headers) &&
		legacyAutoAliasEnabled(a.AutoAliasEnabled) == legacyAutoAliasEnabled(b.AutoAliasEnabled)
}

func v1ProviderHeadersEqual(a, b map[string]string) bool {
	if len(a) == 0 && len(b) == 0 {
		return true
	}
	normalize := func(headers map[string]string) map[string]string {
		out := make(map[string]string, len(headers))
		for key, value := range headers {
			key = strings.ToLower(strings.TrimSpace(key))
			if key == "" {
				continue
			}
			out[key] = strings.TrimSpace(value)
		}
		return out
	}
	return reflect.DeepEqual(normalize(a), normalize(b))
}

func legacyAutoAliasEnabled(value *bool) bool {
	if value == nil {
		return true
	}
	return *value
}

func legacyProviderGroupID(providerID string, ordinal int, used map[string]bool) string {
	id := strings.TrimSpace(providerID)
	if id == "" || used[id] {
		id = fmt.Sprintf("group-%d", ordinal)
		for used[id] {
			ordinal++
			id = fmt.Sprintf("group-%d", ordinal)
		}
	}
	return id
}

func migrateV1ProviderRef(refs map[string]v1ProviderRef, providerID string) (string, string) {
	if ref, ok := refs[providerID]; ok {
		return ref.Provider, ref.Group
	}
	return providerID, DefaultGroupID
}

func migrateV1ProviderPriority(refs map[string]v1ProviderRef, priority []string) []string {
	out := make([]string, 0, len(priority))
	seen := map[string]bool{}
	for _, providerID := range priority {
		providerID = strings.TrimSpace(providerID)
		if providerID == "" {
			continue
		}
		provider, _ := migrateV1ProviderRef(refs, providerID)
		if seen[provider] {
			continue
		}
		seen[provider] = true
		out = append(out, provider)
	}
	return out
}

// --- v2 wire ---

type v2WireConfig struct {
	SchemaVersion       int                 `json:"schema_version"`
	Server              Server              `json:"server"`
	Admin               Admin               `json:"admin"`
	Desktop             Desktop             `json:"desktop"`
	Providers           []v2WireProvider    `json:"providers"`
	Aliases             []v2WireAlias       `json:"aliases"`
	RequestRewriteRules []v2WireRewriteRule `json:"request_rewrite_rules"`
	ProviderPriority    []string            `json:"provider_priority"`
	AutoAliasEnabled    *bool               `json:"auto_alias_enabled"`
}

type v2WireProvider struct {
	ID               string            `json:"id"`
	Name             string            `json:"name"`
	BaseURL          string            `json:"base_url"`
	BaseURLs         []string          `json:"base_urls"`
	BaseURLStrategy  string            `json:"base_url_strategy"`
	Headers          map[string]string `json:"headers"`
	Disabled         bool              `json:"disabled"`
	AutoAliasEnabled *bool             `json:"auto_alias_enabled"`
	Groups           []ProviderGroup   `json:"groups"`
}

func (p *v2WireProvider) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	id := peekJSONString(raw["id"])
	if id == "" {
		id = "?"
	}
	for _, legacy := range []string{"protocol", "api_key", "api_keys", "models", "models_source"} {
		if _, ok := raw[legacy]; ok {
			return fmt.Errorf("v2 provider %q has legacy field %q", id, legacy)
		}
	}
	groupsRaw, ok := raw["groups"]
	if !ok {
		return fmt.Errorf("provider %q missing groups field", id)
	}
	var groups []ProviderGroup
	if err := json.Unmarshal(groupsRaw, &groups); err != nil {
		return fmt.Errorf("provider %q groups: %w", id, err)
	}
	if len(groups) == 0 {
		return fmt.Errorf("provider %q has empty groups", id)
	}
	for _, group := range groups {
		if strings.TrimSpace(group.Protocol) == "" {
			return fmt.Errorf("provider %q group %q missing protocol", id, group.ID)
		}
	}

	type plain struct {
		ID               string            `json:"id"`
		Name             string            `json:"name"`
		BaseURL          string            `json:"base_url"`
		BaseURLs         []string          `json:"base_urls"`
		BaseURLStrategy  string            `json:"base_url_strategy"`
		Headers          map[string]string `json:"headers"`
		Disabled         bool              `json:"disabled"`
		AutoAliasEnabled *bool             `json:"auto_alias_enabled"`
	}
	var out plain
	if err := json.Unmarshal(data, &out); err != nil {
		return err
	}
	p.ID = out.ID
	p.Name = out.Name
	p.BaseURL = out.BaseURL
	p.BaseURLs = out.BaseURLs
	p.BaseURLStrategy = out.BaseURLStrategy
	p.Headers = out.Headers
	p.Disabled = out.Disabled
	p.AutoAliasEnabled = out.AutoAliasEnabled
	p.Groups = groups
	return nil
}

type v2WireAlias struct {
	Alias           string         `json:"alias"`
	DisplayName     string         `json:"display_name"`
	Protocol        string         `json:"protocol"`
	Enabled         bool           `json:"enabled"`
	Targets         []v2WireTarget `json:"targets"`
	AutoGenerated   bool           `json:"auto_generated"`
	Locked          bool           `json:"locked"`
	TargetOrderMode string         `json:"target_order_mode"`
}

type v2WireTarget struct {
	Provider      string `json:"provider"`
	Group         string `json:"group"`
	Model         string `json:"model"`
	Enabled       bool   `json:"enabled"`
	AutoGenerated bool   `json:"auto_generated"`

	groupPresent bool
}

func (t *v2WireTarget) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	_, t.groupPresent = raw["group"]
	type plain struct {
		Provider      string `json:"provider"`
		Group         string `json:"group"`
		Model         string `json:"model"`
		Enabled       bool   `json:"enabled"`
		AutoGenerated bool   `json:"auto_generated"`
	}
	var out plain
	if err := json.Unmarshal(data, &out); err != nil {
		return err
	}
	t.Provider = out.Provider
	t.Group = out.Group
	t.Model = out.Model
	t.Enabled = out.Enabled
	t.AutoGenerated = out.AutoGenerated
	return nil
}

type v2WireRewriteRule struct {
	Name           string                    `json:"name"`
	Alias          string                    `json:"alias"`
	ProviderGroups []ProviderGroupSelector   `json:"provider_groups"`
	Enabled        bool                      `json:"enabled"`
	Override       bool                      `json:"override"`
	Ops            []RequestRewriteOperation `json:"ops"`
	Set            map[string]any            `json:"set"`
	Delete         []string                  `json:"delete"`

	providerGroupsPresent bool
}

func (r *v2WireRewriteRule) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if _, ok := raw["providers"]; ok {
		name := peekJSONString(raw["name"])
		if name == "" {
			name = "?"
		}
		return fmt.Errorf("v2 request rewrite rule %q must not include legacy providers field", name)
	}
	_, r.providerGroupsPresent = raw["provider_groups"]
	type plain struct {
		Name           string                    `json:"name"`
		Alias          string                    `json:"alias"`
		ProviderGroups []ProviderGroupSelector   `json:"provider_groups"`
		Enabled        bool                      `json:"enabled"`
		Override       bool                      `json:"override"`
		Ops            []RequestRewriteOperation `json:"ops"`
		Set            map[string]any            `json:"set"`
		Delete         []string                  `json:"delete"`
	}
	var out plain
	if err := json.Unmarshal(data, &out); err != nil {
		return err
	}
	r.Name = out.Name
	r.Alias = out.Alias
	r.ProviderGroups = out.ProviderGroups
	r.Enabled = out.Enabled
	r.Override = out.Override
	r.Ops = out.Ops
	r.Set = out.Set
	r.Delete = out.Delete
	return nil
}

func decodeV2Config(data []byte) (*Config, error) {
	var wire v2WireConfig
	if err := json.Unmarshal(data, &wire); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	c := Default()
	c.SchemaVersion = CurrentSchemaVersion
	c.Server = wire.Server
	c.Admin = wire.Admin
	c.Desktop = wire.Desktop
	c.ProviderPriority = cloneStrings(wire.ProviderPriority)
	if wire.AutoAliasEnabled != nil {
		c.AutoAliasEnabled = *wire.AutoAliasEnabled
	}

	c.Providers = make([]Provider, 0, len(wire.Providers))
	for _, wp := range wire.Providers {
		p := Provider{
			ID:               wp.ID,
			Name:             wp.Name,
			BaseURL:          wp.BaseURL,
			BaseURLs:         cloneStrings(wp.BaseURLs),
			BaseURLStrategy:  wp.BaseURLStrategy,
			Headers:          cloneStringMap(wp.Headers),
			Disabled:         wp.Disabled,
			AutoAliasEnabled: cloneBoolPtr(wp.AutoAliasEnabled),
			Groups:           cloneProviderGroups(wp.Groups),
		}
		c.Providers = append(c.Providers, p)
	}

	c.Aliases = make([]Alias, 0, len(wire.Aliases))
	for _, wa := range wire.Aliases {
		a := Alias{
			Alias:           wa.Alias,
			DisplayName:     wa.DisplayName,
			Protocol:        wa.Protocol,
			Enabled:         wa.Enabled,
			AutoGenerated:   wa.AutoGenerated,
			Locked:          wa.Locked,
			TargetOrderMode: storageTargetOrderMode(wa.TargetOrderMode),
			Targets:         make([]Target, 0, len(wa.Targets)),
		}
		for _, wt := range wa.Targets {
			group := strings.TrimSpace(wt.Group)
			if !wt.groupPresent || group == "" {
				return nil, fmt.Errorf("alias %q target missing non-empty group", wa.Alias)
			}
			a.Targets = append(a.Targets, Target{
				Provider:      wt.Provider,
				Group:         group,
				Model:         wt.Model,
				Enabled:       wt.Enabled,
				AutoGenerated: wt.AutoGenerated,
			})
		}
		c.Aliases = append(c.Aliases, a)
	}

	c.RequestRewriteRules = make([]RequestRewriteRule, 0, len(wire.RequestRewriteRules))
	for _, wr := range wire.RequestRewriteRules {
		rule := RequestRewriteRule{
			Name:     wr.Name,
			Alias:    wr.Alias,
			Enabled:  wr.Enabled,
			Override: wr.Override,
			Ops:      cloneRequestRewriteOperations(wr.Ops),
			Set:      cloneAnyMap(wr.Set),
			Delete:   cloneStrings(wr.Delete),
		}
		if wr.providerGroupsPresent {
			rule.ProviderGroups = cloneProviderGroupSelectors(wr.ProviderGroups)
			if rule.ProviderGroups == nil {
				rule.ProviderGroups = []ProviderGroupSelector{}
			}
		} else {
			// Omitted provider_groups treated as wildcard empty list for runtime.
			rule.ProviderGroups = []ProviderGroupSelector{}
		}
		c.RequestRewriteRules = append(c.RequestRewriteRules, rule)
	}
	return c, nil
}

func peekJSONString(raw json.RawMessage) string {
	if len(raw) == 0 {
		return ""
	}
	var s string
	if err := json.Unmarshal(raw, &s); err != nil {
		return ""
	}
	return s
}

func cloneBoolPtr(in *bool) *bool {
	if in == nil {
		return nil
	}
	v := *in
	return &v
}

// BackupPathForConfig returns the sibling backup path used before schema upgrades.
func BackupPathForConfig(path string) string {
	return path + ".bak"
}

// NeedsLegacyConfigBackup reports whether base disk bytes are not yet schema v2.
func NeedsLegacyConfigBackup(baseRaw []byte) bool {
	if len(bytes.TrimSpace(baseRaw)) == 0 {
		return false
	}
	var probe struct {
		SchemaVersion json.RawMessage `json:"schema_version"`
	}
	if err := json.Unmarshal(baseRaw, &probe); err != nil {
		return true
	}
	version, legacy, err := parseSchemaVersion(probe.SchemaVersion)
	if err != nil {
		return true
	}
	if legacy {
		return true
	}
	return version != CurrentSchemaVersion
}
